
 Public Class t_ASSalesOrderLine
     Public SalesOrderNumber_K As String 
     Public ReviseCount As  Integer 
     Public SalesOrderLineNumber_K As  Integer 
     Public ProductClass As String 
     Public MainCategoryCode As String 
     Public SubCategoryCode As String 
     Public ItemCode As String 
     Public CustomerPartNumber As String 
     Public Remarks As String 
     Public UnitCode As String 
     Public PackageUnitCode As String 
     Public CartonQuantity As double
     Public UnitPrice As double
     Public OrderQuantity As double
     Public OrderBalanceQuantity As double
     Public ReservedQuantity As double
     Public InstructedQuantity As double
     Public DeliveredQuantity As double
     Public ShippedQuantity As double
     Public OrderBalanceAmount As double
     Public OrderBalanceAmount2 As double
     Public OrderBalanceAmount3 As double
     Public CompletedDate As DateTime 
     Public ProcessMonth As String 
     Public CancelReasonCode As String 
     Public CanceledUserCode As String 
     Public CanceledTransactionNumber As String 
     Public CanceledDate As DateTime 
     Public CreatedUserCode As String 
     Public CreatedTransactionNumber As String 
     Public CreatedDate As DateTime 
     Public ChangedUserCode As String 
     Public ChangedTransactionNumber As String 
     Public ChangedDate As DateTime 
     Public DeletedUserCode As String 
     Public DeletedTransactionNumber As String 
     Public DeletedDate As DateTime 
 End  Class
