
 Public Class QIDR_QualityIssue
     Public ReportRequire As Boolean 
     Public KindOfDoc As String 
     Public CustomerCode As String 
     Public ProductCode As String 
     Public ProductName As String 
     Public DocNo_K As String 
     Public OccurredDate As DateTime 
     Public FactoryName As String 
     Public LotStatus As String 
     Public IssueStatus As String 
     Public FirstDueDate As DateTime 
     Public FirstSubmittedDate As DateTime 
     Public FinalDueDate As DateTime 
     Public FinalSubmittedDate As DateTime 
     Public ClosureDate As DateTime 
     Public Subject As String 
     Public CAForOccurrenceCause As String 
     Public ImplementDateCA As DateTime 
     Public ExpiredDateCA As DateTime 
     Public StatusCA As String 
     Public NoteCA As String 
     Public FileNameCA As String 
     Public FileNameCAServer As String 
     Public PreventiveAction As String 
     Public ImplementDatePA As DateTime 
     Public StatusPA As String 
     Public NotePA As String 
     Public FileNamePA As String 
     Public FileNamePAServer As String 
     Public CAForOutflowCause As String 
     Public ImplementDateCF As DateTime 
     Public ExpiredDateCF As DateTime 
     Public StatusCF As String 
     Public NoteCF As String 
     Public FileNameCF As String 
     Public FileNameCFServer As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public UpdateDate As DateTime 
     Public UpdateUser As String 
 End  Class
