
 Public Class ASP_RequestCodeDetail
     Public GSRNo_K As String 
     Public Code_K As  Integer 
     Public ExpenseID As String 
     Public ItemCode As String 
     Public VietnameseName As String 
     Public EnglishName As String 
     Public Manufacturer As String 
     Public MachineModelSerial As String 
     Public SparePartModel As String 
     Public Origin As String 
     Public BudgetCode As String 
     Public TechnicalSpecification As String 
     Public SafetyRequirement As String 
     Public ColorMatetial As String 
     Public ShapeDemention As String 
     Public UsingPurpose As String 
     Public SupplierCode As String 
     Public SupplierName As String 
     Public PackingType As String 
     Public Unit As String 
     Public UnitPrice As Decimal 
     Public PriceValid As DateTime 
     Public MOQ As Decimal 
     Public LeadTime As  Integer 
     Public Currency As String 
     Public DeliveryTerm As String 
     Public PaymentTerm As String 
     Public PaymentTermDescription As String 
     Public RingiNo As String 
     Public ItemImageFile As String 
     Public ItemImageFileServer As String 
     Public AttachFile As String 
     Public AttachFileServer As String 
     Public AttachFileMSDS As String 
     Public ImportAccountDebit As String 
     Public ImportAccountCredit As String 
     Public ExportAccountDebit As String 
     Public ExportAccountCredit As String 
     Public DestructionProperty As String 
     Public Description As String 
     Public CDStatus As String 
     Public ItemGroup As String 
     Public ItemCode_Temp As String 
     Public VAT As String 
     Public DichVu As  Integer 
     Public ThueNhaThau As String 
     Public HoaChat As Boolean 
 End  Class
