
 Public Class OT_RegisterOT
     Public RegisterOTID_K As String 
     Public OTDate As DateTime 
     Public Priority As Boolean 
     Public SectionName As String 
     Public RQ_ID As String 
     Public RQ_Name As String 
     Public RQ_Mail As String 
     Public RQ_Date As DateTime 
     Public RQ_Comment As String 
     Public LL_ID As String 
     Public LL_Mail As String 
     Public LL_Date As DateTime 
     Public LL_Comment As String 
     Public GL_ID As String 
     Public GL_Mail As String 
     Public GL_Date As DateTime 
     Public GL_Comment As String 
     Public MG_ID As String 
     Public MG_Mail As String 
     Public MG_Date As DateTime 
     Public MG_Comment As String 
     Public DP_ID As String 
     Public DP_Mail As String 
     Public DP_Date As DateTime 
     Public DP_Comment As String 
     Public FB_ID As String 
     Public FB_Mail As String 
     Public FB_Date As DateTime 
     Public FB_Comment As String 
     Public T_ID As String 
     Public T_Mail As String 
     Public T_Date As DateTime 
     Public T_Comment As String 
     Public HR_ID As String 
     Public HR_Mail As String 
     Public HR_Date As DateTime 
     Public HR_Comment As String 
     Public HRCC_ID As String 
     Public HRCC_Mail As String 
     Public CreateDate As DateTime 
     Public CurrentID As String 
     Public SoLan As  Integer 
     Public Path As String 
     Public OK As String 
 End  Class
