
 Public Class WT_Group2
     Public Group2ID_K As String 
     Public GroupID As String 
     Public Group2Name As String 
     Public WDECA1 As  Integer 
     Public WDECA2 As  Integer 
     Public WDECA3 As  Integer 
     Public WDEHC As  Integer 
     Public WDR1CA1 As  Integer 
     Public WDR1CA2 As  Integer 
     Public WDR1CA3 As  Integer 
     Public WDR1HC As  Integer 
     Public WDR2CA1 As  Integer 
     Public WDR2CA2 As  Integer 
     Public WDR2CA3 As  Integer 
     Public WDR2HC As  Integer 
     Public OTECA1 As  Integer 
     Public OTECA2 As  Integer 
     Public OTECA3 As  Integer 
     Public OTEHC As  Integer 
     Public OTVSCA1 As  Integer 
     Public OTVSCA2 As  Integer 
     Public OTVSCA3 As  Integer 
     Public OTVSHC As  Integer 
     Public OTMCA1 As  Integer 
     Public OTMCA2 As  Integer 
     Public OTMCA3 As  Integer 
     Public OTMHC As  Integer 
     Public OTRE1HC As  Integer 
     Public OTRE1CA1 As  Integer 
     Public OTRE1CA2 As  Integer 
     Public OTRE1CA3 As  Integer 
     Public OTRFHC As  Integer 
     Public OTRFCA1 As  Integer 
     Public OTRFCA2 As  Integer 
     Public OTRFCA3 As  Integer 
     Public WDRE1CA1 As  Integer 
     Public WDRE1CA2 As  Integer 
     Public WDRE1CA3 As  Integer 
     Public WDRE1HC As  Integer 
     Public WDRE2CA1 As  Integer 
     Public WDRE2CA2 As  Integer 
     Public WDRE2CA3 As  Integer 
     Public WDRE2HC As  Integer 
     Public WDRFCA1 As  Integer 
     Public WDRFCA2 As  Integer 
     Public WDRFCA3 As  Integer 
     Public WDRFHC As  Integer 
     Public Note As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public UpdateUser As String 
     Public UpdateDate As DateTime 
     Public DeleteDate As DateTime 
     Public DeleteUser As String 
 End  Class
