
 Public Class ES_Approve
     Public ID_K As String 
     Public Leader As String 
     Public LeaderDate As DateTime 
     Public LeaderCmt As String 
     Public LL As String 
     Public LLDate As DateTime 
     Public LLCmt As String 
     Public GL As String 
     Public GLDate As DateTime 
     Public GLCmt As String 
     Public MG As String 
     Public MGDate As DateTime 
     Public MGCmt As String 
     Public DT As String 
     Public DTDate As DateTime 
     Public DTCmt As String 
     Public DTLL As String 
     Public DTLLDate As DateTime 
     Public DTLLCmt As String 
     Public DTGL As String 
     Public DTGLDate As DateTime 
     Public DTGLCmt As String 
     Public DTMG As String 
     Public DTMGDate As DateTime 
     Public DTMGCmt As String 
     Public QCMG As String 
     Public QCMGDate As DateTime 
     Public QCMGCmt As String 
     Public LeaderTT As String 
     Public LeaderDateTT As DateTime 
     Public LeaderCmtTT As String 
     Public LLTT As String 
     Public LLDateTT As DateTime 
     Public LLCmtTT As String 
     Public GLTT As String 
     Public GLDateTT As DateTime 
     Public GLCmtTT As String 
     Public MGTT As String 
     Public MGDateTT As DateTime 
     Public MGCmtTT As String 
     Public QAStaff_TT As String 
     Public QAStaffADate_TT As DateTime 
     Public QAStaffACmt_TT As String 
     Public QAMG_TT As String 
     Public QAMGDate_TT As DateTime 
     Public QAMGCmt_TT As String 
     Public QAStaff As String 
     Public QAStaffADate As DateTime 
     Public QAStaffACmt As String 
     Public QAMG As String 
     Public QAMGDate As DateTime 
     Public QAMGCmt As String 
     Public AE As String 
     Public AEDate As DateTime 
     Public AECmt As String 
     Public DDT As String 
     Public DDTDate As DateTime 
     Public DDTCmt As String 
     Public QAStaff1 As String 
     Public QAStaffADate1 As DateTime 
     Public QAStaffACmt1 As String 
     Public QALL As String 
     Public QALLDate As DateTime 
     Public QALLCmt As String 
     Public QAGL As String 
     Public QAGLDate As DateTime 
     Public QAGLCmt As String 
     Public QAMG1 As String 
     Public QAMGDate1 As DateTime 
     Public QAMGCmt1 As String 
     Public QDP As String 
     Public QDPDate As DateTime 
     Public QDPCmt As String 
     Public TDP As String 
     Public TDPDate As DateTime 
     Public TDPCmt As String 
     Public PDP As String 
     Public PDPDate As DateTime 
     Public PDPCmt As String 
     Public AD1 As String 
     Public AD1Date As DateTime 
     Public AD1Cmt As String 
     Public AD2 As String 
     Public AD2Date As DateTime 
     Public AD2Cmt As String 
     Public AD3 As String 
     Public AD3Date As DateTime 
     Public AD3Cmt As String 
     Public VFM As String 
     Public VFMDate As DateTime 
     Public VFMCmt As String 
     Public FM As String 
     Public FMDate As DateTime 
     Public FMCmt As String 
     Public GD As String 
     Public GDDate As DateTime 
     Public GDCmt As String 
     Public CurrentID As String 
     Public ApproveDate As DateTime 
     Public FinalEvaluate As String 
     Public Status As String 
     Public LyDoTraVe As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
 End  Class
