
 Public Class ASP_Supplier_History
     Public SRNo As String 
     Public SupplierCode_K As String 
     Public SupplierName As String 
     Public Address As String 
     Public Telephone As String 
     Public Fax As String 
     Public TaxCode As String 
     Public ContactName1 As String 
     Public ContactName2 As String 
     Public ContactName3 As String 
     Public ContactName4 As String 
     Public VendorPolicyFileName As String 
     Public VendorPolicyFileServer As String 
     Public RingiNo As String 
     Public RingiFileName As String 
     Public RingiFileServer As String 
     Public PrincipleContractFileName As String 
     Public PrincipleContractFileServer As String 
     Public InvestmentLicenceFileName As String 
     Public InvestmentLicenceFileServer As String 
     Public BankFileName As String 
     Public BankFileServer As String 
     Public BankName1 As String 
     Public OtherDocument As String 
     Public BranchOrProvince1 As String 
     Public AccountNumber1 As String 
     Public AccountCurrency1 As String 
     Public Benificiary1 As String 
     Public PaymentDoc1 As String 
     Public PaymentTerm1 As String 
     Public PaymentDescription1 As String 
     Public BankName2 As String 
     Public BranchOrProvince2 As String 
     Public AccountCurrency2 As String 
     Public AccountNumber2 As String 
     Public Benificiary2 As String 
     Public PaymentDoc2 As String 
     Public PaymentTerm2 As String 
     Public PaymentDescription2 As String 
     Public BankName3 As String 
     Public BranchOrProvince3 As String 
     Public AccountCurrency3 As String 
     Public AccountNumber3 As String 
     Public Benificiary3 As String 
     Public PaymentDoc3 As String 
     Public PaymentTerm3 As String 
     Public PaymentDescription3 As String 
     Public Purchaser As String 
     Public SupplierCodeOld As String 
     Public Category As String 
     Public Classification As String 
     Public Note As String 
     Public Active As Boolean 
     Public DeactivateReason As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
 End  Class
