
 Public Class ASP_ItemList
     Public ItemCode_K As String 
     Public ItemNameV As String 
     Public ItemNameE As String 
     Public BudgetCode As String 
     Public Manufacturer As String 
     Public MachineModelSerial As String 
     Public SparePartModel As String 
     Public Origin As String 
     Public TechnicalSpecification As String 
     Public SafetyRequirement As String 
     Public ColorMatetial As String 
     Public ShapeDemention As String 
     Public UsingPurpose As String 
     Public SupplierCode As String 
     Public SupplierName As String 
     Public PackingType As String 
     Public Unit As String 
     Public UnitPrice As Decimal 
     Public PriceValid As DateTime 
     Public MOQ As Decimal 
     Public LeadTime As  Integer 
     Public Currency As String 
     Public DeliveryTerm As String 
     Public PaymentTerm As String 
     Public PaymentTermDescription As String 
     Public RingiNo As String 
     Public ItemImageFile As String 
     Public ItemImageFileServer As String 
     Public AttachFile As String 
     Public AttachFileServer As String 
     Public ImportAccountDebit As String 
     Public ImportAccountCredit As String 
     Public ExportAccountDebit As String 
     Public ExportAccountCredit As String 
     Public DestructionProperty As String 
     Public CDStatus As String 
     Public Description As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public ApproveUser As String 
     Public ApproveDate As DateTime 
     Public EditUser As String 
     Public EditDate As DateTime 
     Public EditApproveUser As String 
     Public EditApproveDate As DateTime 
     Public Dept As String 
     Public StatusDisable As Boolean 
     Public UserDisable As String 
     Public DateDisable As DateTime 
     Public ReasonDisable As String 
     Public ItemGroup As String 
     Public ExpenseID As String 
     Public VAT As String 
     Public DichVu As  Integer 
     Public ThueNhaThau As String 
     Public HoaChat As Boolean 
 End  Class
