
 Public Class BS_NhanVienDen
     Public ID_K As String 
     Public TenKH As String 
     Public ChucVu As String 
     Public SoID As String 
     Public NguoiDoiUng As String 
     Public CuDiem As String 
     Public DiaChiEmail As String 
     Public GioDen As DateTime 
     Public NgayDen As DateTime 
     Public ChuyenBayDen As String 
     Public GaDen As String 
     Public NoiDuaDen As String 
     Public GioNhanPhong As DateTime 
     Public GioDi As DateTime 
     Public NgayDi As DateTime 
     Public ChuyenBayDi As String 
     Public GaDi As String 
     Public NoiXuatPhat As String 
     Public GioBay As DateTime 
     Public CanXeDuaDonSanBay As Boolean 
     Public XeDon As String 
     Public TaiXeDon As String 
     Public SDTDon As String 
     Public LoaiXeDon As String 
     Public BienSoXeDon As String 
     Public XeTien As String 
     Public TaiXeTien As String 
     Public SDTTien As String 
     Public LoaiXeTien As String 
     Public BienSoXeTien As String 
     Public KhachDiChungXeDon As String 
     Public KhachDiChungXeTien As String 
     Public CanKhachSan As Boolean 
     Public SoNgayLuuTru As  Integer 
     Public TenKhachSan As String 
     Public LoaiPhong As String 
     Public GiaPhong1Dem As Decimal 
     Public GiaXeDonSanBay As Decimal 
     Public GiatUi As  Integer 
     Public TraPhongTre As String 
     Public GioTraPhongTre As DateTime 
     Public PhongHutThuoc As String 
     Public NguoiThanhToan As String 
     Public GiaXeTienSanBay As Decimal 
     Public UuDaiKhac As String 
     Public CanDoSach As Boolean 
     Public SizeDoSach As String 
     Public SizeGiaySach As String 
     Public SizeAoKhoac As String 
     Public YeuCauKhac As String 
     Public CanVisa As Boolean 
     Public NopHoSo As Boolean 
     Public NhanKetQua As Boolean 
     Public NgayTraKetQua As DateTime 
     Public CongVanChapNhan As String 
     Public CanComTrua As Boolean 
     Public LoaiCom As String 
     Public SoNgayDungCom As  Integer 
     Public NgayDauDungCom As DateTime 
     Public NgayCuoiDungCom As DateTime 
     Public GhiChu As String 
     Public LuuTru As Boolean 
     Public CreateDate As DateTime 
     Public CreateUser As String 
 End  Class
