
 Public Class CF_CapacityFD
     Public Ngay_K As DateTime 
     Public Customer As String 
     Public ProductCode_K As String 
     Public Lotsize As  Integer 
     Public SameFD As String 
     Public LotPerDay As Decimal 
     Public KPcsPerDay As Decimal 
     Public KPcsPerwk As Decimal 
     Public KPcsPermonth As Decimal 
     Public KPcsPermonthHLD As Decimal 
     Public ProcessName As String 
     Public TM1_TG As Decimal 
     Public TM1_SL As Decimal 
     Public TM1_Lot As Decimal 
     Public TM1KPcs As Decimal 
     Public TM2_TG As Decimal 
     Public TM2_SL As Decimal 
     Public TM2_Lot As Decimal 
     Public TM2Kpcs As Decimal 
     Public DD1_TG As Decimal 
     Public DD1_SL As Decimal 
     Public DD1_Lot As Decimal 
     Public DD1Kpcs As Decimal 
     Public DD2_TG As Decimal 
     Public DD2_SL As Decimal 
     Public DD2_Lot As Decimal 
     Public DD2Kpcs As Decimal 
     Public DD3_TG As Decimal 
     Public DD3_SL As Decimal 
     Public DD3_Lot As Decimal 
     Public DD3Kpcs As Decimal 
     Public DH_TG As Decimal 
     Public DH_SL As Decimal 
     Public DH_Lot As Decimal 
     Public DHKpcs As Decimal 
     Public DS0_TG As Decimal 
     Public DS0_SL As Decimal 
     Public DS0_Lot As Decimal 
     Public DS0Kpcs As Decimal 
     Public DS0Same As String 
     Public DC0_TG As Decimal 
     Public DC0_SL As Decimal 
     Public DC0_Lot As Decimal 
     Public DC0Kpcs As Decimal 
     Public DT0_TG As Decimal 
     Public DT0_SL As Decimal 
     Public DT0_Lot As Decimal 
     Public DT0Kpcs As Decimal 
     Public DS1_TG As Decimal 
     Public DS1_SL As Decimal 
     Public DS1_Lot As Decimal 
     Public DS1Kpcs As Decimal 
     Public DS1Same As String 
     Public HourPerDay As  Integer 
 End  Class
