
 Public Class EMM_B00Detail
     Public Code_K As String 
     Public IncomingDate As DateTime 
     Public InspectionDate As DateTime 
     Public PdCode As String 
     Public MaterialLotNo As String 
     Public ActualTotalQuantity As Decimal 
     Public AcceptanceQualityLimits As  Integer 
     Public CheckProcess As String 
     Public Error001 As Decimal 
     Public Error002 As Decimal 
     Public Error003 As Decimal 
     Public Error004 As Decimal 
     Public Error005 As Decimal 
     Public Error006 As Decimal 
     Public Error007 As Decimal 
     Public Error009 As Decimal 
     Public Error011 As Decimal 
     Public Error013 As Decimal 
     Public Error016 As Decimal 
     Public Error017 As Decimal 
     Public Error018 As Decimal 
     Public Error021 As Decimal 
     Public Error101 As Decimal 
     Public Error102 As Decimal 
     Public Error103 As Decimal 
     Public Error104 As Decimal 
     Public Error105 As Decimal 
     Public Error106 As Decimal 
     Public Error107 As Decimal 
     Public Error108 As Decimal 
     Public Error109 As Decimal 
     Public Error110 As Decimal 
     Public Error111 As Decimal 
     Public Error112 As Decimal 
     Public Error113 As Decimal 
     Public Error115 As Decimal 
     Public Error117 As Decimal 
     Public Error118 As Decimal 
     Public Error122 As Decimal 
     Public Error123 As Decimal 
     Public Error125 As Decimal 
     Public Error126 As Decimal 
     Public Error130 As Decimal 
     Public Error201 As Decimal 
     Public Error202 As Decimal 
     Public Error204 As Decimal 
     Public Error205 As Decimal 
     Public Error206 As Decimal 
     Public Error207 As Decimal 
     Public Error208 As Decimal 
     Public Error209 As Decimal 
     Public Error219 As Decimal 
     Public Error234 As Decimal 
     Public Error225 As Decimal 
     Public Error506 As Decimal 
     Public Error601 As Decimal 
     Public Error602 As Decimal 
     Public Error603 As Decimal 
     Public Error607 As Decimal 
     Public Error608 As Decimal 
     Public Error610 As Decimal 
     Public Error629 As Decimal 
     Public Error634 As Decimal 
     Public Error635 As Decimal 
     Public Error636 As Decimal 
     Public Error637 As Decimal 
     Public Percent001 As Decimal 
     Public Percent002 As Decimal 
     Public Percent003 As Decimal 
     Public Percent004 As Decimal 
     Public Percent005 As Decimal 
     Public Percent006 As Decimal 
     Public Percent007 As Decimal 
     Public Percent009 As Decimal 
     Public Percent011 As Decimal 
     Public Percent013 As Decimal 
     Public Percent016 As Decimal 
     Public Percent017 As Decimal 
     Public Percent018 As Decimal 
     Public Percent021 As Decimal 
     Public Percent101 As Decimal 
     Public Percent102 As Decimal 
     Public Percent103 As Decimal 
     Public Percent104 As Decimal 
     Public Percent105 As Decimal 
     Public Percent106 As Decimal 
     Public Percent107 As Decimal 
     Public Percent108 As Decimal 
     Public Percent109 As Decimal 
     Public Percent110 As Decimal 
     Public Percent111 As Decimal 
     Public Percent112 As Decimal 
     Public Percent113 As Decimal 
     Public Percent115 As Decimal 
     Public Percent117 As Decimal 
     Public Percent118 As Decimal 
     Public Percent122 As Decimal 
     Public Percent123 As Decimal 
     Public Percent125 As Decimal 
     Public Percent126 As Decimal 
     Public Percent130 As Decimal 
     Public Percent201 As Decimal 
     Public Percent202 As Decimal 
     Public Percent204 As Decimal 
     Public Percent205 As Decimal 
     Public Percent206 As Decimal 
     Public Percent207 As Decimal 
     Public Percent208 As Decimal 
     Public Percent209 As Decimal 
     Public Percent219 As Decimal 
     Public Percent234 As Decimal 
     Public Percent225 As Decimal 
     Public Percent506 As Decimal 
     Public Percent601 As Decimal 
     Public Percent602 As Decimal 
     Public Percent603 As Decimal 
     Public Percent607 As Decimal 
     Public Percent608 As Decimal 
     Public Percent610 As Decimal 
     Public Percent629 As Decimal 
     Public Percent634 As Decimal 
     Public Percent635 As Decimal 
     Public Percent636 As Decimal 
     Public Percent637 As Decimal 
     Public SamplingEvaluation As String 
     Public TestReportEvaluation As String 
     Public FinalEvaluation As String 
     Public Treatment As String 
     Public Start As DateTime 
     Public Finish As DateTime 
     Public Inspector As String 
     Public Remark As String 
     Public UpdateUser As String 
     Public UpdateDate As DateTime 
 End  Class
