
 Public Class FIX_TheTSCD
     Public IFRS_K As String 
     Public OldSection As String 
     Public NewSectiton As String 
     Public GAPreparedID As String 
     Public GAPreparedName As String 
     Public GAPreparedMail As String 
     Public GAPreparedDate As DateTime 
     Public GAPreparedComment As String 
     Public GAApprovedID As String 
     Public GAApprovedMail As String 
     Public GAApprovedDate As DateTime 
     Public GAApprovedComment As String 
     Public PBCheckedID As String 
     Public PBCheckedMail As String 
     Public PBCheckedDate As DateTime 
     Public PBCheckedComment As String 
     Public PBApprovedID As String 
     Public PBApprovedMail As String 
     Public PBApprovedDate As DateTime 
     Public PBApprovedComment As String 
     Public LOCheckedID As String 
     Public LOCheckedMail As String 
     Public LOCheckedDate As DateTime 
     Public LOCheckedComment As String 
     Public LOApprovedID As String 
     Public LOApprovedMail As String 
     Public LOApprovedDate As DateTime 
     Public LOApprovedComment As String 
     Public ACCheckedID As String 
     Public ACCheckedMail As String 
     Public ACCheckedDate As DateTime 
     Public ACCheckedComment As String 
     Public ACApprovedID As String 
     Public ACApprovedMail As String 
     Public ACApprovedDate As DateTime 
     Public ACApprovedComment As String 
     Public GAReceivedID As String 
     Public GAReceivedMail As String 
     Public GAReceivedDate As DateTime 
     Public GAReceivedComment As String 
     Public PBNRevisedID As String 
     Public PBNRevisedMail As String 
     Public PBNRevisedDate As DateTime 
     Public PBNRevisedComment As String 
     Public PBNApprovedID As String 
     Public PBNApprovedMail As String 
     Public PBNApprovedDate As DateTime 
     Public PBNApprovedComment As String 
     Public LONCheckedID As String 
     Public LONCheckedMail As String 
     Public LONCheckedDate As DateTime 
     Public LONCheckedComment As String 
     Public LONApprovedID As String 
     Public LONApprovedMail As String 
     Public LONApprovedDate As DateTime 
     Public LONApprovedComment As String 
     Public CurrentID As String 
     Public CreateDate As DateTime 
 End  Class
