
 Public Class FIX_QDThanhLy
     Public IFRS_K As String 
     Public Section As String 
     Public PBCheckedID As String 
     Public PBCheckedName As String 
     Public PBCheckedMail As String 
     Public PBCheckedDate As DateTime 
     Public PBCheckedComment As String 
     Public PBApprovedID As String 
     Public PBApprovedMail As String 
     Public PBApprovedDate As DateTime 
     Public PBApprovedComment As String 
     Public LOCheckedID As String 
     Public LOCheckedMail As String 
     Public LOCheckedDate As DateTime 
     Public LOCheckedComment As String 
     Public LOApprovedID As String 
     Public LOApprovedMail As String 
     Public LOApprovedDate As DateTime 
     Public LOApprovedComment As String 
     Public ACCheckedID As String 
     Public ACCheckedMail As String 
     Public ACCheckedDate As DateTime 
     Public ACCheckedComment As String 
     Public ACApprovedID As String 
     Public ACApprovedMail As String 
     Public ACApprovedDate As DateTime 
     Public ACApprovedComment As String 
     Public GAReceiveddID As String 
     Public GAReceivedMail As String 
     Public GAReceivedDate As DateTime 
     Public GAReceivedComment As String 
     Public GAApprovedID As String 
     Public GAApprovedMail As String 
     Public GAApprovedDate As DateTime 
     Public GAApprovedComment As String 
     Public CurrentID As String 
     Public CreateDate As DateTime 
     Public TenTiengAnh As String 
     Public TenTiengViet As String 
     Public QDSo As String 
     Public LoaiTaiSan As String 
     Public Model As String 
     Public ThoiGianSuDung As String 
     Public NgayNhap As DateTime 
     Public LyDoThanhLy As String 
     Public CoTKHaiQuan As Boolean 
     Public MaToKhai As String 
     Public NgayQDThanhLy As DateTime 
     Public PhuongPhapThanhLy As String 
     Public GiaTriThuHoi As Decimal 
     Public ChiPhiThanhLy As Decimal 
     Public NgayTienHanhTL As DateTime 
     Public NguyenGia As Decimal 
     Public GiaConLai As Decimal 
     Public NgayKetThucKhauHao As DateTime 
     Public NgayGhiGiamSoTSCD As DateTime 
     Public Khac As String 
 End  Class
