
 Public Class FIX_BBDiDoi
     Public ID_K As String 
     Public PBCheckedID As String 
     Public PBCheckedName As String 
     Public PBCheckedMail As String 
     Public PBCheckedDate As DateTime 
     Public PBCheckedComment As String 
     Public PBApprovedID As String 
     Public PBApprovedMail As String 
     Public PBApprovedDate As DateTime 
     Public PBApprovedComment As String 
     Public PBNCheckedID As String 
     Public PBNCheckedMail As String 
     Public PBNCheckedDate As DateTime 
     Public PBNCheckedComment As String 
     Public PBNApprovedID As String 
     Public PBNApprovedMail As String 
     Public PBNApprovedDate As DateTime 
     Public PBNApprovedComment As String 
     Public ACCheckedID As String 
     Public ACCheckedMail As String 
     Public ACCheckedDate As DateTime 
     Public ACCheckedComment As String 
     Public ACApprovedID As String 
     Public ACApprovedMail As String 
     Public ACApprovedDate As DateTime 
     Public ACApprovedComment As String 
     Public GACheckedID As String 
     Public GACheckedMail As String 
     Public GACheckedDate As DateTime 
     Public GACheckedComment As String 
     Public GAApprovedID As String 
     Public GAApprovedMail As String 
     Public GAApprovedDate As DateTime 
     Public GAApprovedComment As String 
     Public CurrentID As String 
     Public CreateDate As DateTime 
     Public MaTSCD As String 
     Public TenTiengAnh As String 
     Public TenTiengViet As String 
     Public SectionOut As String 
     Public CoThue As Boolean 
     Public NoiDatTSCDCu As String 
     Public ViTriCu As String 
     Public NgayChuyenDi As DateTime 
     Public LyDoChuyenDi As String 
     Public SectionIn As String 
     Public NoiDatTSCDMoi As String 
     Public ViTriMoi As String 
     Public NgayNhapVao As DateTime 
     Public KhoanMucKinhPhiCu As String 
     Public KhoanMucKinhPhiMoi As String 
     Public NgayXuLy As DateTime 
     Public SoModel As String 
 End  Class
