
 Public Class GSR_GoodsOrderDetail
     Public ID_K As String 
     Public OrderID_K As  Integer 
     Public JCode As String 
     Public JName As String 
     Public PackingUnit As String 
     Public MinQty As Decimal 
     Public Unit As String 
     Public Quantity As Decimal 
     Public DeliveryDate As DateTime 
     Public ConfirmDate As DateTime 
     Public LateDays As String 
     Public DeliveryDays As  Integer 
     Public LeadtimeRequest As  Integer 
     Public NotePU As String 
     Public Note As String 
     Public ETADate As DateTime 
     Public ETD_SDocs As DateTime 
     Public ETA_SDocs As DateTime 
     Public ETADate2 As DateTime 
     Public POID As String 
     Public ShippingTerm As String 
     Public TDPRPO As String 
     Public ReceivedQty As Decimal 
     Public CountReceived As  Integer 
     Public VendorCode As String 
     Public VendorName As String 
     Public ReceivedUser As String 
     Public ReceivedDate As DateTime 
     Public DelayReason As String 
     Public EditedReason As String 
     Public ActionPrevent As String 
     Public BeforePrice As Decimal 
     Public UnitPrice As Decimal 
     Public CurrencyCode As String 
     Public UnitPriceUSD As Decimal 
     Public RedBill As String 
     Public ACDate As DateTime 
     Public ScheduleDate As DateTime 
     Public ExpectedDate As DateTime 
     Public InvoiceID As String 
     Public LastVendorCode As String 
     Public LastVendorName As String 
     Public LO_ConfirmedDate As DateTime 
     Public LO_ConfirmedPO As Boolean 
     Public LO_Note As String 
 End  Class
