
 Public Class MFPC_Data
     Public SerialNo_K As String 
     Public Factory As String 
     Public IssuedDate As DateTime 
     Public DetectedDate As DateTime 
     Public CustomerName As String 
     Public ProductType As String 
     Public ProductName As String 
     Public ProductCode As String 
     Public LotNo As String 
     Public MotSanPham As Boolean 
     Public DefectCode As String 
     Public DetectedProcess As String 
     Public DefectMode As String 
     Public LotCount As  Integer 
     Public LotSize As  Integer 
     Public DefectQuantity As String 
     Public TL As Decimal 
     Public Detail As String 
     Public LyDoTre As String 
     Public Treatment As String 
     Public Price As Decimal 
     Public Damage As Decimal 
     Public SL2 As String 
     Public TL2 As Decimal 
     Public Rank As String 
     Public FileName1 As String 
     Public FileName2 As String 
     Public FileName3 As String 
     Public FileName4 As String 
     Public FileName5 As String 
     Public FileName6 As String 
     Public FileName7 As String 
     Public FileName8 As String 
     Public FileName9 As String 
     Public FileName10 As String 
     Public FileNameH1 As String 
     Public FileNameH2 As String 
     Public FileNameH3 As String 
     Public FileNameS1 As String 
     Public FileNameS2 As String 
     Public FileNameS3 As String 
     Public FileNameS4 As String 
     Public Hinh1 As String 
     Public Hinh2 As String 
     Public FileKH1 As String 
     Public FileKH2 As String 
     Public FileKH3 As String 
     Public FileName1_Server As String 
     Public FileName2_Server As String 
     Public FileName3_Server As String 
     Public FileName4_Server As String 
     Public FileName5_Server As String 
     Public FileName6_Server As String 
     Public FileName7_Server As String 
     Public FileName8_Server As String 
     Public FileName9_Server As String 
     Public FileName10_Server As String 
     Public FileNameH1_Server As String 
     Public FileNameH2_Server As String 
     Public FileNameH3_Server As String 
     Public FileNameS1_Server As String 
     Public FileNameS2_Server As String 
     Public FileNameS3_Server As String 
     Public FileNameS4_Server As String 
     Public Hinh1_Server As String 
     Public Hinh2_Server As String 
     Public FileKH1_Server As String 
     Public FileKH2_Server As String 
     Public FileKH3_Server As String 
     Public S_InvesCause As String 
     Public S_CauseOuflow As String 
     Public S_ProcessHappend As String 
     Public S_RejectLot As String 
     Public S_CCause1 As String 
     Public S_CCause2 As String 
     Public S_CCause3 As String 
     Public S_CCause4 As String 
     Public S_CCause5 As String 
     Public S_CCType1 As String 
     Public S_CCType2 As String 
     Public S_CCType3 As String 
     Public S_CPerson1 As String 
     Public S_CPerson2 As String 
     Public S_CPerson3 As String 
     Public S_CPerson4 As String 
     Public S_CPerson5 As String 
     Public S_CDueDate1 As DateTime 
     Public S_CDueDate2 As DateTime 
     Public S_CDueDate3 As DateTime 
     Public S_CDueDate4 As DateTime 
     Public S_CDueDate5 As DateTime 
     Public S_PracticedDate1 As DateTime 
     Public S_PracticedDate2 As DateTime 
     Public S_PracticedDate3 As DateTime 
     Public S_PracticedDate4 As DateTime 
     Public S_PracticedDate5 As DateTime 
     Public S_OCause1 As String 
     Public S_OCause2 As String 
     Public S_OCause3 As String 
     Public S_OType1 As String 
     Public S_OType2 As String 
     Public S_OType3 As String 
     Public S_OPerson1 As String 
     Public S_OPerson2 As String 
     Public S_OPerson3 As String 
     Public S_ODueDate1 As DateTime 
     Public S_ODueDate2 As DateTime 
     Public S_ODueDate3 As DateTime 
     Public S_OPracticedDate1 As DateTime 
     Public S_OPracticedDate2 As DateTime 
     Public S_OPracticedDate3 As DateTime 
     Public Man As Boolean 
     Public Method As Boolean 
     Public Machine As Boolean 
     Public Material As Boolean 
     Public Design As Boolean 
     Public Everonment As Boolean 
     Public BCKP As DateTime 
     Public LydoBCTre As String 
     Public SA_Monitoring As String 
     Public SA_CheckRepetition As String 
     Public SA_CheckCapability As String 
     Public SA_CheckRejectRate As String 
     Public SA_Detail1 As String 
     Public SA_Detail2 As String 
     Public SA_Detail3 As String 
     Public SA_Person1 As String 
     Public SA_Person2 As String 
     Public SA_Person3 As String 
     Public SA_DueDate1 As DateTime 
     Public SA_DueDate2 As DateTime 
     Public SA_DueDate3 As DateTime 
     Public SA_PracticeDate1 As DateTime 
     Public SA_PracticeDate2 As DateTime 
     Public SA_PracticeDate3 As DateTime 
     Public PP_InspectStock As String 
     Public PP_ResultInspectStock As String 
     Public PP_Action As String 
     Public CS_CheckShipping As String 
     Public CS_FindCustomer As String 
     Public CS_Action As String 
     Public Status As String 
     Public MaDangLuc As String 
     Public GhiChu As String 
     Public GhiChuMay As String 
     Public LoaiSCQT As String 
     Public NgayCDPhatSinhSuCo As DateTime 
 End  Class
