
 Public Class PCM_TrayU00
     Public YMD_K As String 
     Public ECode_K As String 
     Public PdCode_K As String 
     Public JCode_K As String 
     Public SubPrcName_K As String 
     Public PrcName As String 
     Public JEName As String 
     Public JVName As String 
     Public UnitLot As Decimal 
     Public Unit As String 
     Public MinQty As Decimal 
     Public StdDtbtQty As Decimal 
     Public AddDtbtQty As Decimal 
     Public LotS1 As  Integer 
     Public LotE1 As  Integer 
     Public Bal1 As Decimal 
     Public MatQty1 As Decimal 
     Public LotS2 As  Integer 
     Public LotE2 As  Integer 
     Public Bal2 As Decimal 
     Public MatQty2 As Decimal 
     Public LotS3 As  Integer 
     Public LotE3 As  Integer 
     Public Bal3 As Decimal 
     Public MatQty3 As Decimal 
     Public AdjustLot As  Integer 
     Public AdjustQty As Decimal 
     Public ActReceive As Decimal 
     Public Note As String 
     Public RequestQty As Decimal 
     Public RequestDate As DateTime 
     Public Old As Boolean 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public UpdateDate As DateTime 
     Public UpdateUser As String 
     Public Lock1 As Boolean 
     Public Lock2 As Boolean 
     Public Lock3 As Boolean 
     Public Time1Date As DateTime 
     Public Time2Date As DateTime 
     Public Time3Date As DateTime 
     Public PCNo As String 
     Public DeptName As String 
 End  Class
