
 Public Class PEM_QLSC
     Public ID_K As String 
     Public Ngay As DateTime 
     Public PhongBan As String 
     Public SoMay As String 
     Public MachineCode As String 
     Public MachineName As String 
     Public LoaiMay As String 
     Public ViTriMay As String 
     Public LoaiSuCo As String 
     Public NhanVien As String 
     Public CaLamViec As String 
     Public HienTrang As String 
     Public CacBuocKiemTra As String 
     Public NguyenNhanSuCo As String 
     Public CachKhacPhuc As String 
     Public DoiSach As String 
     Public TGThucHien As String 
     Public HoanThanhDoiSach As String 
     Public DamTrach As String 
     Public DuLieuSuCo As String 
     Public TGPS1 As DateTime 
     Public PENhan2 As DateTime 
     Public PEDen3 As DateTime 
     Public PETim4 As DateTime 
     Public PECoPhuTung5 As DateTime 
     Public PESuaChua6 As DateTime 
     Public PEBanGiao7 As DateTime 
     Public P21 As  Integer 
     Public P32 As  Integer 
     Public P43 As  Integer 
     Public P54 As  Integer 
     Public P65 As  Integer 
     Public P76 As  Integer 
     Public Tong71 As  Integer 
     Public XacNhan As String 
     Public NgayHoanThanh As DateTime 
     Public ThayTheThietBi As String 
     Public DoDac As String 
     Public Maker As String 
     Public BaoDuong As String 
     Public CaiTien As String 
     Public KTVS As String 
     Public NoiDungCV As String 
     Public HienTrangTruoc As String 
     Public TenPhuTung As String 
     Public SLThayThe As String 
     Public TonKho As String 
     Public Model As String 
     Public ViTriLapDat As String 
     Public ThoiGianSuDung As String 
     Public ThayDinhKy As String 
     Public TGKT As String 
     Public TGKTTiep As DateTime 
     Public CoKhi As String 
     Public Dien As String 
     Public AnToan As String 
     Public DanhGia As String 
     Public GhiNhanFileGiay As String 
     Public GhiChu As String 
     Public XacNhanDaXong As Boolean 
     Public Prepared As String 
     Public PreparedDate As DateTime 
     Public PreparedCmt As String 
     Public LL As String 
     Public LLDate As DateTime 
     Public LLCmt As String 
     Public GL As String 
     Public GLDate As DateTime 
     Public GLCmt As String 
     Public MG As String 
     Public MGDate As DateTime 
     Public MGCmt As String 
     Public CurrentID As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
 End  Class
