
 Public Class PM_Pacemarker
     Public PMDate_K As DateTime 
     Public ID_K As String 
     Public Shift As String 
     Public TableNo As  Integer 
     Public SeatNo As  Integer 
     Public EyeInsTotal As  Integer 
     Public MicInsTotal As  Integer 
     Public EyeFailed As  Integer 
     Public MicFailed As  Integer 
     Public StartDate As DateTime 
     Public EndDate As DateTime 
     Public SDate As DateTime 
     Public EDate As DateTime 
     Public TableWorkID As String 
     Public EmployeeID As String 
     Public Status As Boolean 
     Public EyeSuspendTime As  Integer 
     Public MicSuspendTime As  Integer 
     Public EyeInsTime As  Integer 
     Public MicInsTime As  Integer 
     Public EmpName As String 
     Public EmpEntryDate As DateTime 
     Public GroupID As String 
     Public ProductID As String 
     Public Lot As String 
     Public Process As String 
     Public ProcessCode As String 
     Public Piece As  Integer 
     Public EyeInsPace As  Integer 
     Public MicInsPace As  Integer 
     Public m2 As double
     Public StandardOKRatio As  Integer 
     Public TBGEye As double
     Public TBGMic As double
     Public EyeRate As  Integer 
     Public MicRate As  Integer 
     Public EyeSuspend As  Integer 
     Public MicSuspend As  Integer 
     Public EyeInsPiece As  Integer 
     Public MicInsPiece As  Integer 
     Public ProductCode As String 
     Public LotNo As String 
     Public Pn As String 
     Public PdCodeReason As String 
     Public TBG As String 
     Public TBGReason As String 
     Public Rate As String 
     Public RateReason As String 
     Public Suspend As String 
     Public SuspendReason As String 
     Public TotalPcs As String 
     Public AddPcs As  Integer 
     Public TotalPcsReason As String 
     Public OT As  Integer 
     Public AVG As double
     Public WorkMonth As  Integer 
     Public IsLocked As Boolean 
 End  Class
