
 Public Class QAE_Abnormal
     Public ID_K As String 
     Public Section As String 
     Public RequestDate As DateTime 
     Public CurrentID As String 
     Public PIC As String 
     Public PICComment As String 
     Public PICDate As DateTime 
     Public Checked As String 
     Public CheckedComment As String 
     Public CheckedDate As DateTime 
     Public Approved As String 
     Public ApprovedComment As String 
     Public ApprovedDate As DateTime 
     Public QAPIC As String 
     Public QAPICComment As String 
     Public QAPICDate As DateTime 
     Public QAChecked As String 
     Public QACheckedComment As String 
     Public QACheckedDate As DateTime 
     Public QAApproved As String 
     Public QAApprovedComment As String 
     Public QAApprovedDate As DateTime 
     Public MaThietBi As String 
     Public TenThietBiDoV As String 
     Public NgayPhatSinh As DateTime 
     Public NoiDung As String 
     Public SanPhamDo As String 
     Public MucDichDo As String 
     Public ThuocTinhDo As String 
     Public ChuanSanPham As String 
     Public XacNhanAnhHuong As String 
     Public XacNhanKhongAnhHuong As String 
     Public PhamViSanPhamKhongPhuHop As String 
     Public KQXacNhanQA As String 
     Public XuLySanPham As String 
     Public BaoCaoKhachHang As String 
     Public XuLyDungCu As String 
     Public XuLyDungCuKhac As String 
     Public KQXuLy As String 
     Public AttachedFile As String 
     Public AttachedFileServer As String 
     Public CreatedDate As DateTime 
     Public CreatedUser As String 
 End  Class
