
 Public Class QI_ClaimIssueD3
     Public ClaimIssueID_K As String 
     Public DueDate2 As DateTime 
     Public DueDate3 As DateTime 
     Public Prepared As String 
     Public PreparedComment As String 
     Public PreparedDate As DateTime 
     Public PIC2 As String 
     Public PICComment2 As String 
     Public PICDate2 As DateTime 
     Public Checked2 As String 
     Public CheckedComment2 As String 
     Public CheckedDate2 As DateTime 
     Public Approved2 As String 
     Public ApprovedComment2 As String 
     Public ApprovedDate2 As DateTime 
     Public CheckedCS2 As String 
     Public CheckedCommentCS2 As String 
     Public CheckedDateCS2 As DateTime 
     Public ApprovedCS2 As String 
     Public ApprovedCommentCS2 As String 
     Public ApprovedDateCS2 As DateTime 
     Public PIC3 As String 
     Public PICComment3 As String 
     Public PICDate3 As DateTime 
     Public Checked3 As String 
     Public CheckedComment3 As String 
     Public CheckedDate3 As DateTime 
     Public Approved3 As String 
     Public ApprovedComment3 As String 
     Public ApprovedDate3 As DateTime 
     Public CheckedCS3 As String 
     Public CheckedCommentCS3 As String 
     Public CheckedDateCS3 As DateTime 
     Public ApprovedCS3 As String 
     Public ApprovedCommentCS3 As String 
     Public ApprovedDateCS3 As DateTime 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public UpdateDate As DateTime 
     Public UpdateUser As String 
     Public CurrentUser2 As String 
     Public CurrentUser3 As String 
     Public Status As String 
 End  Class
