
 Public Class RRP_ReportRiceDaily
     Public ECode_K As String 
     Public YMD_K As String 
     Public Dept As String 
     Public Grp As String 
     Public Phone As String 
     Public EName As String 
     Public HCAC1M As  Integer 
     Public HCAC1C As  Integer 
     Public HCAC2M As  Integer 
     Public HCAC2C As  Integer 
     Public HCAC2C4 As  Integer 
     Public HCACBS As  Integer 
     Public HCTC1M As  Integer 
     Public HCTC1C As  Integer 
     Public HCTC1BS As  Integer 
     Public HCTC1C4 As  Integer 
     Public HCAN1C2 As  Integer 
     Public HCAN1C2C As  Integer 
     Public C1AC1M As  Integer 
     Public C1AC1C As  Integer 
     Public C1AC2M As  Integer 
     Public C1AC2C As  Integer 
     Public C1AC3M As  Integer 
     Public C1AC3C As  Integer 
     Public C1ACBS As  Integer 
     Public C1TC1M As  Integer 
     Public C1TC2M As  Integer 
     Public C1TC1BS As  Integer 
     Public C1TC1C As  Integer 
     Public C1TCMThem As  Integer 
     Public C1TCCThem As  Integer 
     Public C1TC1Sua As  Integer 
     Public C1AN1C2 As  Integer 
     Public C1AN2C2 As  Integer 
     Public C1AN1C As  Integer 
     Public C2AC1M As  Integer 
     Public C2AC1C As  Integer 
     Public C2AC2M As  Integer 
     Public C2AC2C As  Integer 
     Public C2ACBS As  Integer 
     Public C2TC1M As  Integer 
     Public C2TC1BS As  Integer 
     Public C2TC1C As  Integer 
     Public C2TCMThem As  Integer 
     Public C2TCCThem As  Integer 
     Public C2TC1Sua As  Integer 
     Public C2AN1C2 As  Integer 
     Public C2AN1C As  Integer 
     Public C3AC1M As  Integer 
     Public C3AC1C As  Integer 
     Public C3AC2M As  Integer 
     Public C3AC2C As  Integer 
     Public C3AC3M As  Integer 
     Public C3AC3C As  Integer 
     Public C3AC1BS As  Integer 
     Public C3AC1Sua As  Integer 
     Public C3TC1M As  Integer 
     Public C3TC1BS As  Integer 
     Public C3TC1C As  Integer 
     Public C3TC1Sua As  Integer 
     Public C3AN1C2 As  Integer 
     Public C3AN1C As  Integer 
     Public Note As String 
     Public Deleted As Boolean 
     Public ApproveHC As Boolean 
     Public ApproveC1 As Boolean 
     Public ApproveC2 As Boolean 
     Public ApproveC3 As Boolean 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public UpdateUser As String 
     Public UpdateDate As DateTime 
     Public StatusApprove As Boolean 
     Public StandardQty As  Integer 
     Public HCACBauA As  Integer 
     Public HCACBauB As  Integer 
     Public C1ACBauA As  Integer 
     Public C1ACBauB As  Integer 
     Public C2ACBauA As  Integer 
     Public C2ACBauB As  Integer 
     Public C3ACBauA As  Integer 
     Public C3ACBauB As  Integer 
     Public C1ACC4 As  Integer 
     Public C2ACC4 As  Integer 
     Public C3ACC4 As  Integer 
     Public C1TCC2Them As  Integer 
     Public C1TCC4Them As  Integer 
     Public C2TCC2Them As  Integer 
     Public C2TCC4Them As  Integer 
     Public C1TC1C4 As  Integer 
     Public C1TC2C4 As  Integer 
     Public C2TC1C4 As  Integer 
     Public C3TC1C4 As  Integer 
     Public C3AC1Chao As  Integer 
 End  Class
