
 Public Class SWTFC_SummaryCompareACT
     Public Date_K As DateTime 
     Public GroupID_K As String 
     Public CustomerCode_K As String 
     Public LotQty As Decimal 
     Public PcsQty As Decimal 
     Public M2Qty As Decimal 
     Public M2PerHr As Decimal 
     Public PcsPerHr As Decimal 
     Public TotalWT As Decimal 
     Public PcsPerTotal As Decimal 
     Public M2PerTotal As Decimal 
     Public BM As Decimal 
     Public Target As Decimal 
     Public Person As Decimal 
     Public K101 As Decimal 
     Public K102 As Decimal 
     Public K108 As Decimal 
     Public K110 As Decimal 
     Public K120 As Decimal 
     Public K103 As Decimal 
     Public K104 As Decimal 
     Public K105 As Decimal 
     Public K106 As Decimal 
     Public K107 As Decimal 
     Public K111 As Decimal 
     Public K112 As Decimal 
     Public K113 As Decimal 
     Public K114 As Decimal 
     Public K115 As Decimal 
     Public K116 As Decimal 
     Public K117 As Decimal 
     Public K118 As Decimal 
     Public K119 As Decimal 
     Public K121 As Decimal 
     Public K122 As Decimal 
     Public K123 As Decimal 
     Public K124 As Decimal 
     Public K125 As Decimal 
     Public K126 As Decimal 
     Public K199 As Decimal 
     Public K202 As Decimal 
     Public K203 As Decimal 
     Public K204 As Decimal 
     Public K205 As Decimal 
     Public K206 As Decimal 
     Public K207 As Decimal 
     Public K211 As Decimal 
     Public K212 As Decimal 
     Public K213 As Decimal 
     Public K214 As Decimal 
     Public K215 As Decimal 
     Public K216 As Decimal 
     Public K217 As Decimal 
     Public K218 As Decimal 
     Public K219 As Decimal 
     Public K220 As Decimal 
     Public K221 As Decimal 
     Public K222 As Decimal 
     Public K223 As Decimal 
     Public K224 As Decimal 
     Public K225 As Decimal 
     Public K226 As Decimal 
     Public K299 As Decimal 
     Public C101 As Decimal 
     Public C102 As Decimal 
     Public C108 As Decimal 
     Public C110 As Decimal 
     Public C120 As Decimal 
     Public C103 As Decimal 
     Public C104 As Decimal 
     Public C105 As Decimal 
     Public C106 As Decimal 
     Public C107 As Decimal 
     Public C111 As Decimal 
     Public C112 As Decimal 
     Public C113 As Decimal 
     Public C114 As Decimal 
     Public C115 As Decimal 
     Public C116 As Decimal 
     Public C117 As Decimal 
     Public C118 As Decimal 
     Public C119 As Decimal 
     Public C121 As Decimal 
     Public C122 As Decimal 
     Public C123 As Decimal 
     Public C124 As Decimal 
     Public C125 As Decimal 
     Public C126 As Decimal 
     Public C199 As Decimal 
     Public C202 As Decimal 
     Public C203 As Decimal 
     Public C204 As Decimal 
     Public C205 As Decimal 
     Public C206 As Decimal 
     Public C207 As Decimal 
     Public C211 As Decimal 
     Public C212 As Decimal 
     Public C213 As Decimal 
     Public C214 As Decimal 
     Public C215 As Decimal 
     Public C216 As Decimal 
     Public C217 As Decimal 
     Public C218 As Decimal 
     Public C219 As Decimal 
     Public C220 As Decimal 
     Public C221 As Decimal 
     Public C222 As Decimal 
     Public C223 As Decimal 
     Public C224 As Decimal 
     Public C225 As Decimal 
     Public C226 As Decimal 
     Public C299 As Decimal 
     Public DiffKQCV As Decimal 
     Public DiffWasteTime As Decimal 
     Public Standard As Decimal 
     Public IsLock As Boolean 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public LockDate As DateTime 
     Public LockUser As String 
 End  Class
