
 Public Class UDM_LogisticsPaymentHistory
     Public ID_K As String 
     Public LogisticType As String 
     Public Idx As  Integer 
     Public DebitNote As String 
     Public AWBOrBL As String 
     Public Supplier As String 
     Public Incoterm As String 
     Public ComInvoice As String 
     Public ETA As String 
     Public NEV As String 
     Public CW As Decimal 
     Public GW As Decimal 
     Public Cont20 As Decimal 
     Public Cont40 As Decimal 
     Public CBM As Decimal 
     Public Destination As String 
     Public Flight As String 
     Public Domestics As Decimal 
     Public Trucking As Decimal 
     Public CFS As Decimal 
     Public SpecialHandlingCharge As Decimal 
     Public StorageCharge As Decimal 
     Public SpecialStorageCharge As Decimal 
     Public THC As Decimal 
     Public PortCharge As Decimal 
     Public Detention As Decimal 
     Public Demurrage As Decimal 
     Public OceanFee As Decimal 
     Public AirFee As Decimal 
     Public LocalCharge As Decimal 
     Public DestinationCharge As Decimal 
     Public FOBCharge As Decimal 
     Public DOFee As Decimal 
     Public BLOrAWB As Decimal 
     Public Serrender As Decimal 
     Public TelexRelease As Decimal 
     Public LiftOnOrLiftOff As Decimal 
     Public TerminalFee As Decimal 
     Public Fuel As Decimal 
     Public Security As Decimal 
     Public CIC As Decimal 
     Public PortChargeVND As Decimal 
     Public InlandCharge As Decimal 
     Public CustomsClearance As Decimal 
     Public AirFeeVND As Decimal 
     Public DutyAndTax As Decimal 
     Public Packing As Decimal 
     Public Fumigation As Decimal 
     Public SealFee As Decimal 
     Public Total As Decimal 
     Public Total1 As Decimal 
     Public Note As String 
     Public VATNo As String 
     Public MM As String 
     Public YYYY As String 
     Public Time As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
 End  Class
