
 Public Class UDM_TLHead
     Public ID_K As String 
     Public PhongBan As String 
     Public NgayYeuCau As DateTime 
     Public LyDo As String 
     Public PhanLoai As String 
     Public Prepared As String 
     Public PreparedDate As DateTime 
     Public PreparedCmt As String 
     Public CheckedMG As String 
     Public CheckedMGDate As DateTime 
     Public CheckedMGCmt As String 
     Public ConfirmDM As String 
     Public ConfirmDMDate As DateTime 
     Public ConfirmDMCmt As String 
     Public Confirm1 As String 
     Public Confirm1Cmt As String 
     Public Confirm1Date As DateTime 
     Public Confirm2 As String 
     Public Confirm2Cmt As String 
     Public Confirm2Date As DateTime 
     Public Confirm3 As String 
     Public Confirm3Cmt As String 
     Public Confirm3Date As DateTime 
     Public PUConfirm1 As String 
     Public PUConfirmDate1 As DateTime 
     Public PUConfirmCmt1 As String 
     Public ApprovedFM As String 
     Public ApprovedFMDate As DateTime 
     Public ApprovedFMCmt As String 
     Public ITConfirm As String 
     Public ITConfirmDate As DateTime 
     Public ITConfirmCmt As String 
     Public LOConfirm As String 
     Public LOConfirmDate As DateTime 
     Public LOConfirmCmt As String 
     Public SEConfirm As String 
     Public SEConfirmDate As DateTime 
     Public SEConfirmCmt As String 
     Public PUConfirm As String 
     Public PUConfirmDate As DateTime 
     Public PUConfirmCmt As String 
     Public CurrentMail As String 
 End  Class
