
 Public Class UDM_ExCustomsDeclaration
     Public ID_K As String 
     Public CDNo As String 
     Public RegDate As DateTime 
     Public FinishedDate As DateTime 
     Public DocsName As String 
     Public Exporter As String 
     Public Importer As String 
     Public AuthorisedParty As String 
     Public CustomsBroker As  Integer 
     Public Forwarder As  Integer 
     Public ExportMode As  Integer 
     Public InvestmentCertificate As String 
     Public ICDate As DateTime 
     Public ICFinishedDate As DateTime 
     Public DocsDate As DateTime 
     Public DocsFinishedDate As DateTime 
     Public InvoiceNo As String 
     Public PackingListNo As String 
     Public DestinationPort As String 
     Public LoadingPort As String 
     Public ImportingCountry As String 
     Public Transportation As String 
     Public DeliveryTerms As  Integer 
     Public PaymentTerms As String 
     Public Currency As String 
     Public ER As Decimal 
     Public NetWeight As Decimal 
     Public GrossWeight As Decimal 
     Public PackageNo As  Integer 
     Public PalletNo As  Integer 
     Public TotalAmount As Decimal 
     Public Cont20 As  Integer 
     Public Cont40 As  Integer 
     Public DocsNo As String 
     Public ReImportDate As DateTime 
     Public AWB As String 
     Public AWBDate As DateTime 
     Public AWBFile As String 
     Public AWBFileServer As String 
     Public CW As Decimal 
     Public CBM As Decimal 
     Public GWAWB As Decimal 
     Public CartonTotal As  Integer 
     Public NDVTruckQty As  Integer 
     Public NewTruckQty As  Integer 
     Public Reason As String 
     Public ExtraAWB As Boolean 
     Public Remark As String 
     Public Status As  Integer 
     Public LockDate As DateTime 
     Public LockUser As String 
     Public UnLockDate As DateTime 
     Public UnLockUser As String 
     Public OriginalCDReceivedDate As DateTime 
     Public IncludeInvOrPL As Boolean 
     Public IncludeDocsName As Boolean 
     Public IncludeBill As Boolean 
     Public CSPrintDate As DateTime 
     Public ChildMode As String 
     Public PO As String 
     Public PODate As DateTime 
     Public POFinishedDate As DateTime 
     Public OvertimeSunday As Boolean 
     Public OvertimeInspection As Boolean 
     Public CommodityCode As String 
     Public MeansOfTransportation As String 
     Public CustomsName As String 
     Public EstimatedRegisterDate As DateTime 
     Public EstimatedWHCode As String 
     Public EstimatedTransMean As String 
     Public ETD As DateTime 
     Public InvoiceCode As String 
     Public InvoiceNumber As String 
     Public InvoiceDate As DateTime 
     Public PriceInvoiceCode As String 
     Public FlightOrVessel As String 
     Public WarehourseCode As String 
     Public NEVReceivedDate As DateTime 
     Public PxhFileAttach As String 
     Public PxhFileServer As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public UpdateDate As DateTime 
     Public UpdateUser As String 
 End  Class
