
 Public Class WT_AGLHistory
     Public ID_K As String 
     Public DateOfCard As DateTime 
     Public EmployeeID As String 
     Public EmployeeName As String 
     Public Shift As String 
     Public GroupID As String 
     Public GroupName As String 
     Public Group2ID As String 
     Public Group2Name As String 
     Public Job As String 
     Public WD As Decimal 
     Public OT As Decimal 
     Public STime As String 
     Public ETime As String 
     Public TimeIn As String 
     Public TimeOut As String 
     Public Total As Decimal 
     Public AnGiaiLaoRC As  Integer 
     Public AnGiaiLaoB As  Integer 
     Public AnGiaiLaoL As  Integer 
     Public AnGiaiLaoFT As  Integer 
     Public AnGiaiLaoKQCV As  Integer 
     Public InAGLUser As  Integer 
     Public InAGL As  Integer 
     Public OutAGL As  Integer 
     Public OutAGLUser As  Integer 
     Public DiffAGL As  Integer 
     Public VeSinhRC As  Integer 
     Public VeSinhB As  Integer 
     Public VeSinhL As  Integer 
     Public VeSinhFT As  Integer 
     Public VeSinhKQCV As  Integer 
     Public InVSUser As  Integer 
     Public InVS As  Integer 
     Public OutVS As  Integer 
     Public OutVSUser As  Integer 
     Public DiffVS As  Integer 
     Public HopRC As  Integer 
     Public HopB As  Integer 
     Public HopL As  Integer 
     Public HopFT As  Integer 
     Public HopKQCV As  Integer 
     Public InHopUser As  Integer 
     Public InHop As  Integer 
     Public OutHop As  Integer 
     Public OutHopUser As  Integer 
     Public DiffHop As  Integer 
     Public Note As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
 End  Class
