
 Public Class WT_Group2_Time
     Public Group2ID_K As String 
     Public GroupID As String 
     Public Group2Name As String 
     Public WDECA1 As DateTime 
     Public WDECA2 As DateTime 
     Public WDECA3 As DateTime 
     Public WDEHC As DateTime 
     Public WDR1CA1 As DateTime 
     Public WDR1CA2 As DateTime 
     Public WDR1CA3 As DateTime 
     Public WDR1HC As DateTime 
     Public WDR2CA1 As DateTime 
     Public WDR2CA2 As DateTime 
     Public WDR2CA3 As DateTime 
     Public WDR2HC As DateTime 
     Public OTECA1 As DateTime 
     Public OTECA2 As DateTime 
     Public OTECA3 As DateTime 
     Public OTEHC As DateTime 
     Public OTVSCA1 As DateTime 
     Public OTVSCA2 As DateTime 
     Public OTVSCA3 As DateTime 
     Public OTVSHC As DateTime 
     Public OTMCA1 As DateTime 
     Public OTMCA2 As DateTime 
     Public OTMCA3 As DateTime 
     Public OTMHC As DateTime 
     Public OTRE1HC As DateTime 
     Public OTRE1CA1 As DateTime 
     Public OTRE1CA2 As DateTime 
     Public OTRE1CA3 As DateTime 
     Public OTRFHC As DateTime 
     Public OTRFCA1 As DateTime 
     Public OTRFCA2 As DateTime 
     Public OTRFCA3 As DateTime 
     Public WDRE1CA1 As DateTime 
     Public WDRE1CA2 As DateTime 
     Public WDRE1CA3 As DateTime 
     Public WDRE1HC As DateTime 
     Public WDRE2CA1 As DateTime 
     Public WDRE2CA2 As DateTime 
     Public WDRE2CA3 As DateTime 
     Public WDRE2HC As DateTime 
     Public WDRFCA1 As DateTime 
     Public WDRFCA2 As DateTime 
     Public WDRFCA3 As DateTime 
     Public WDRFHC As DateTime 
     Public Note As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public UpdateUser As String 
     Public UpdateDate As DateTime 
     Public DeleteDate As DateTime 
     Public DeleteUser As String 
 End  Class
