
 Public Class WTFC_StandardUnit_SX_BK
     Public ID_K As String 
     Public GroupCode As String 
     Public ProductCode_K As String 
     Public ComponentCode_K As String 
     Public ProcessNumber_K As String 
     Public ProcessCode As String 
     Public ProcessName As String 
     Public FactoryCode As String 
     Public FactoryName As String 
     Public ChildComponent As String 
     Public UnitCode As String 
     Public UnitName As String 
     Public CustomerCode As String 
     Public CustomerName As String 
     Public StdWTSHT As Decimal 
     Public StdWTPC As Decimal 
     Public Note As String 
     Public U00 As Decimal 
     Public LotPerCycle As Decimal 
     Public LengthDevice As Decimal 
     Public Rate As Decimal 
     Public Rate2 As Decimal 
     Public Rate3 As Decimal 
     Public BeginCycle As Decimal 
     Public MidCycle As Decimal 
     Public SheetPerCycle As Decimal 
     Public Size As Decimal 
     Public Distance As Decimal 
     Public SheetPerFrame As Decimal 
     Public FramePerPlating As Decimal 
     Public LotCount As Decimal 
     Public MachineCount As Decimal 
     Public Person As Decimal 
     Public StdRate As Decimal 
     Public ComponentShapeFlag As String 
     Public StandardLotSize As Decimal 
     Public ComponentWidth As Decimal 
     Public ComponentLength As Decimal 
     Public ConversionValue1 As Decimal 
     Public ConversionValue2 As Decimal 
     Public RevisionCode As String 
     Public PurposeName2 As String 
 End  Class
