
 Public Class WTFC_WorkTime_BK
     Public GroupCode As String 
     Public ForecastID As String 
     Public ProductCode As String 
     Public ComponentCode As String 
     Public ProcessNumber As String 
     Public ProcessCode As String 
     Public ProcessName As String 
     Public ChildCc As String 
     Public UnitCode As String 
     Public CustomerCode As String 
     Public CustomerName As String 
     Public TotalInputSHT As Decimal 
     Public TotalInputPC As Decimal 
     Public TotalInputSHTAll As Decimal 
     Public TotalInputPCAll As Decimal 
     Public SQMQty As Decimal 
     Public TotalInputM As Decimal 
     Public TotalInputLot As Decimal 
     Public TotalInputCycle As Decimal 
     Public SoLanMa As Decimal 
     Public StdWTSHT As Decimal 
     Public StdWTPC As Decimal 
     Public Std112 As Decimal 
     Public WorkTime As Decimal 
     Public WTPerson As Decimal 
     Public StdWorkTime As Decimal 
     Public StdWorkTime112 As Decimal 
     Public LotCount As  Integer 
     Public MachineCount As  Integer 
     Public Person As  Integer 
     Public StdRate As Decimal 
     Public M2PerPcs As Decimal 
     Public MidCycle As Decimal 
     Public LengthDevice As Decimal 
     Public SheetPerFrame As Decimal 
     Public FramePerPlating As Decimal 
     Public ForecastDate As DateTime 
 End  Class
