
 Public Class ASP_EditItem
     Public YMD_K As String 
     Public ItemCode As String 
     Public ItemNameV As String 
     Public ItemNameE As String 
     Public BudgetCode As String 
     Public Manufacturer As String 
     Public MachineModelSerial As String 
     Public SparePartModel As String 
     Public Origin As String 
     Public TechnicalSpecification As String 
     Public SafetyRequirement As String 
     Public ColorMatetial As String 
     Public ShapeDemention As String 
     Public UsingPurpose As String 
     Public SupplierCode As String 
     Public SupplierName As String 
     Public PackingType As String 
     Public Unit As String 
     Public UnitPrice As Decimal 
     Public PriceValid As DateTime 
     Public MOQ As Decimal 
     Public LeadTime As  Integer 
     Public Currency As String 
     Public DeliveryTerm As String 
     Public PaymentTerm As String 
     Public PaymentTermDescription As String 
     Public RingiNo As String 
     Public ItemImageFile As String 
     Public ItemImageFileServer As String 
     Public AttachFile As String 
     Public AttachFileServer As String 
     Public ImportAccountDebit As String 
     Public ImportAccountCredit As String 
     Public ExportAccountDebit As String 
     Public ExportAccountCredit As String 
     Public DestructionProperty As String 
     Public CDStatus As String 
     Public Description As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public RequestSection As String 
     Public RequestDate As DateTime 
     Public Prepared As String 
     Public PreparedComment As String 
     Public PreparedStatus As Boolean 
     Public PreparedDate As DateTime 
     Public Checked As String 
     Public CheckedComment As String 
     Public CheckedStatus As Boolean 
     Public CheckedDate As DateTime 
     Public Approved As String 
     Public ApprovedComment As String 
     Public ApprovedStatus As Boolean 
     Public ApprovedDate As DateTime 
     Public Finished As Boolean 
     Public ItemGroup As String 
     Public ExpenseID As String 
     Public VAT As String 
 End  Class
