
 Public Class LOA_StockIn
     Public ID_K As String 
     Public VoucherNo As String 
     Public VoucherDate As DateTime 
     Public ReceivingDate As DateTime 
     Public SupplierCode As String 
     Public SupplierName As String 
     Public Currency As String 
     Public ExchangeRate As Decimal 
     Public ItemCode As String 
     Public ItemName As String 
     Public Unit As String 
     Public Qty As Decimal 
     Public UnitPrice As Decimal 
     Public Amount As Decimal 
     Public AmountUSD As Decimal 
     Public NetAmount As Decimal 
     Public TaxCode As String 
     Public TaxRate As Decimal 
     Public TaxAmount As Decimal 
     Public InvoiceNumber As String 
     Public InvoiceDate As DateTime 
     Public AccountingCode As String 
     Public DebitCreditFlag As String 
     Public PurchaseOrders As String 
     Public Section As String 
     Public Position As String 
     Public QtyConvert As Decimal 
     Public StockOutQty As Decimal 
     Public StockQty As Decimal 
     Public GoodQty As Decimal 
     Public DamagedQty As Decimal 
     Public HoldQty As Decimal 
     Public VoucherTypeID As String 
     Public EmployeeID As String 
     Public ObjectTypeID As String 
     Public VATTypeID As String 
     Public DebitAccountID As String 
     Public CreditAccountID As String 
     Public Ana02ID As String 
     Public CurrencyWHT As String 
     Public TLWHT As Decimal 
     Public DebitAccountNT As String 
     Public CreditAccountNT As String 
     Public Decription As String 
     Public ProductType As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
 End  Class
