
 Public Class ASP_SupplierRequest
     Public SRNo_K As String 
     Public RequestSection As String 
     Public RequestDate As DateTime 
     Public PUPrepared As String 
     Public PUPreparedComment As String 
     Public PUPreparedStatus As Boolean 
     Public PUPreparedDate As DateTime 
     Public PUChecked As String 
     Public PUCheckedComment As String 
     Public PUCheckedStatus As Boolean 
     Public PUCheckedDate As DateTime 
     Public PUApproved As String 
     Public PUApprovedComment As String 
     Public PUApprovedStatus As Boolean 
     Public PUApprovedDate As DateTime 
     Public Finished As Boolean 
     Public SupplierCode As String 
     Public SupplierName As String 
     Public Address As String 
     Public Telephone As String 
     Public Fax As String 
     Public TaxCode As String 
     Public ContactName1 As String 
     Public ContactName2 As String 
     Public ContactName3 As String 
     Public ContactName4 As String 
     Public VendorPolicyFileName As String 
     Public VendorPolicyFileServer As String 
     Public RingiFileName As String 
     Public RingiFileServer As String 
     Public PrincipleContractFileName As String 
     Public PrincipleContractFileServer As String 
     Public InvestmentLicenceFileName As String 
     Public InvestmentLicenceFileServer As String 
     Public OtherDocument As String 
     Public BankFileName As String 
     Public BankFileServer As String 
     Public PaymentDoc1 As String 
     Public PaymentTerm1 As String 
     Public PaymentDescription1 As String 
     Public Purchaser As String 
     Public Category As String 
     Public Classification As String 
     Public Note As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public ConfirmDate As DateTime 
     Public ConfirmUser As String 
     Public IsConfirm As Boolean 
 End  Class
