
 Public Class PLM_FC_MAT
     Public Tuan_K As DateTime 
     Public ItemCode_K As String 
     Public GSRQty As  Integer 
     Public TTStock As  Integer 
     Public DT1 As  Integer 
     Public DT2 As  Integer 
     Public DT3 As  Integer 
     Public DT4 As  Integer 
     Public DT5 As  Integer 
     Public DT6 As  Integer 
     Public DT7 As  Integer 
     Public DT8 As  Integer 
     Public DT9 As  Integer 
     Public DT10 As  Integer 
     Public DT11 As  Integer 
     Public DT12 As  Integer 
     Public DT13 As  Integer 
     Public DT14 As  Integer 
     Public DT15 As  Integer 
     Public DT16 As  Integer 
     Public DT17 As  Integer 
     Public DT18 As  Integer 
     Public DT19 As  Integer 
     Public DT20 As  Integer 
     Public DT21 As  Integer 
     Public DT22 As  Integer 
     Public DT23 As  Integer 
     Public DT24 As  Integer 
     Public BWH As  Integer 
     Public LO As  Integer 
     Public SITE As  Integer 
     Public NC1 As  Integer 
     Public NC2 As  Integer 
     Public NC3 As  Integer 
     Public NC4 As  Integer 
     Public NC5 As  Integer 
     Public NC6 As  Integer 
     Public NC7 As  Integer 
     Public NC8 As  Integer 
     Public NC9 As  Integer 
     Public NC10 As  Integer 
     Public NC11 As  Integer 
     Public NC12 As  Integer 
     Public NC13 As  Integer 
     Public NC14 As  Integer 
     Public NC15 As  Integer 
     Public NC16 As  Integer 
     Public NC17 As  Integer 
     Public NC18 As  Integer 
     Public NC19 As  Integer 
     Public NC20 As  Integer 
     Public NC21 As  Integer 
     Public NC22 As  Integer 
     Public NC23 As  Integer 
     Public NC24 As  Integer 
     Public HV1 As  Integer 
     Public HV2 As  Integer 
     Public HV3 As  Integer 
     Public HV4 As  Integer 
     Public HV5 As  Integer 
     Public HV6 As  Integer 
     Public HV7 As  Integer 
     Public HV8 As  Integer 
     Public HV9 As  Integer 
     Public HV10 As  Integer 
     Public HV11 As  Integer 
     Public HV12 As  Integer 
     Public HV13 As  Integer 
     Public HV14 As  Integer 
     Public HV15 As  Integer 
     Public HV16 As  Integer 
     Public HV17 As  Integer 
     Public HV18 As  Integer 
     Public HV19 As  Integer 
     Public HV20 As  Integer 
     Public HV21 As  Integer 
     Public HV22 As  Integer 
     Public HV23 As  Integer 
     Public HV24 As  Integer 
 End  Class
