
 Public Class KQQC_NgoaiQuan
    Public ID_K As String
    Public Ngay As DateTime
    Public STT As Integer
    Public MSSP As String
    Public Lot As String
    Public KhachHang As String
    Public Method As String
    Public CongDoan As String
    Public SoLanTest As Integer
    Public SoLuongKiem As Integer
    Public SoLuongLoi As Integer
    Public TyLe As Decimal
    Public DanhGiaLoiNgoaiQuan As String
    Public DanhGiaKichThuocDuongMach As String
    Public DanhGiaLoHang As String
    Public SoMayRoi As String
    Public QuangLuong As String
    Public TocDo As Decimal
    Public ApLuc As String

    Public Error001_01 As Integer
    Public Error002_01 As Integer
    Public Error003_01 As Integer
    Public Error004_01 As Integer
    Public Error005_01 As Integer
    Public Error006_01 As Integer
    Public Error007_01 As Integer
    Public Error009_01 As Integer
    Public Error012_01 As Integer
    Public Error016_01 As Integer
    Public Error018_01 As Integer
    Public Error024_01 As Integer
    Public Error025_01 As Integer
    Public Error627_01 As Integer
    Public Error639_01 As Integer
    Public ThoiGian_01 As Integer
    Public MSNV_01 As String

    Public Error001_02 As Integer
    Public Error002_02 As Integer
    Public Error003_02 As Integer
    Public Error004_02 As Integer
    Public Error005_02 As Integer
    Public Error006_02 As Integer
    Public Error007_02 As Integer
    Public Error009_02 As Integer
    Public Error012_02 As Integer
    Public Error016_02 As Integer
    Public Error018_02 As Integer
    Public Error024_02 As Integer
    Public Error025_02 As Integer
    Public Error627_02 As Integer
    Public Error639_02 As Integer
    Public ThoiGian_02 As Integer
    Public MSNV_02 As String

    Public Error001_03 As Integer
    Public Error002_03 As Integer
    Public Error003_03 As Integer
    Public Error004_03 As Integer
    Public Error005_03 As Integer
    Public Error006_03 As Integer
    Public Error007_03 As Integer
    Public Error009_03 As Integer
    Public Error012_03 As Integer
    Public Error016_03 As Integer
    Public Error018_03 As Integer
    Public Error024_03 As Integer
    Public Error025_03 As Integer
    Public Error627_03 As Integer
    Public Error639_03 As Integer
    Public ThoiGian_03 As Integer
    Public MSNV_03 As String

    Public Error001_04 As Integer
    Public Error002_04 As Integer
    Public Error003_04 As Integer
    Public Error004_04 As Integer
    Public Error005_04 As Integer
    Public Error006_04 As Integer
    Public Error007_04 As Integer
    Public Error009_04 As Integer
    Public Error012_04 As Integer
    Public Error016_04 As Integer
    Public Error018_04 As Integer
    Public Error024_04 As Integer
    Public Error025_04 As Integer
    Public Error627_04 As Integer
    Public Error639_04 As Integer
    Public ThoiGian_04 As Integer
    Public MSNV_04 As String

    Public Error001_Cavity As String
    Public Error002_Cavity As String
    Public Error003_Cavity As String
    Public Error004_Cavity As String
    Public Error005_Cavity As String
    Public Error006_Cavity As String
    Public Error007_Cavity As String
    Public Error009_Cavity As String
    Public Error012_Cavity As String
    Public Error016_Cavity As String
    Public Error018_Cavity As String
    Public Error024_Cavity As String
    Public Error025_Cavity As String
    Public Error627_Cavity As String
    Public Error639_Cavity As String
    Public ThoiGian_Cavity As Integer
    Public MSNV_Cavity As String

    Public PhuongPhapXuLy As String
    Public GhiChu As String

    Public CreateUser As String
    Public CreateDate As DateTime
End  Class
