
 Public Class CP_Import_UV_9304
     Public ProcessCode As DateTime 
     Public Ngay As DateTime 
     Public Customer As String 
     Public ProductCode_K As String 
     Public StartLot As  Integer 
     Public T1 As  Integer 
     Public T2 As  Integer 
     Public T3 As  Integer 
     Public T4 As  Integer 
     Public T5 As  Integer 
     Public T6 As  Integer 
     Public T7 As  Integer 
     Public T8 As  Integer 
     Public T9 As  Integer 
     Public T10 As  Integer 
     Public L1 As  Integer 
     Public L2 As  Integer 
     Public L3 As  Integer 
     Public L4 As  Integer 
     Public L5 As  Integer 
     Public L6 As  Integer 
     Public L7 As  Integer 
     Public L8 As  Integer 
     Public L9 As  Integer 
     Public L10 As  Integer 
     Public EdnLot As  Integer 
     Public K1 As  Integer 
     Public K2 As  Integer 
     Public K3 As  Integer 
     Public K4 As  Integer 
     Public K5 As  Integer 
     Public K6 As  Integer 
     Public K7 As  Integer 
     Public K8 As  Integer 
     Public K9 As  Integer 
     Public K10 As  Integer 
     Public StartLot2 As  Integer 
     Public F1 As  Integer 
     Public F2 As  Integer 
     Public F3 As  Integer 
     Public F4 As  Integer 
     Public F5 As  Integer 
     Public F6 As  Integer 
     Public F7 As  Integer 
     Public F8 As  Integer 
     Public F9 As  Integer 
     Public F10 As  Integer 
 End  Class
