
 Public Class KQQC_KQCVNew
     Public ID_K As String 
     Public Ngay As DateTime 
     Public ProductCode As String 
     Public LotNo As String 
     Public Customer As String 
     Public Method As String 
     Public SoTo As  Integer 
     Public SoMay As String 
     Public SoLanTest As String 
     Public Qty As  Integer 
     Public TotalTime As  Integer 
     Public QtyDefect As  Integer 
     Public RatioDefect As Decimal 
     Public ModeEvaluate As String 
     Public Pattan As String 
     Public ProductCheck As String 
     Public QCCheck As String 
     Public PhuongPhap As String 
     Public XacNhan As String 
     Public GhiChu As String 
     Public QuangLuong As Decimal 
     Public TocDoETC As Decimal 
     Public TyLeLoi As String 
     Public ThoiGianKiem As  Integer 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public Q001 As  Integer 
     Public Q002 As  Integer 
     Public Q003 As  Integer 
     Public Q004 As  Integer 
     Public Q005 As  Integer 
     Public Q006 As  Integer 
     Public Q007 As  Integer 
     Public Q009 As  Integer 
     Public Q012 As  Integer 
     Public Q024 As  Integer 
     Public Q025 As  Integer 
     Public Q627 As  Integer 
     Public Q639 As  Integer 
     Public QOther As  Integer 
     Public M As  Integer 
 End  Class
