
 Public Class MC_ListRequest
     Public ID_K As String 
     Public ProductCode_K As String 
     Public LotNo_K As String 
     Public Customer As String 
     Public Method As String 
     Public CatHangKhoSF As Boolean 
     Public CatHangKhoPI As Boolean 
     Public NgamHang As Boolean 
     Public CatHangNgam As Boolean 
     Public DoDoBung As Boolean 
     Public DoDoCung As Boolean 
     Public DoKichThuoc As Boolean 
     Public DoFlatness As Boolean 
     Public DoProfile As Boolean 
     Public DoVescan As Boolean 
     Public KeoHangKhoSF As Boolean 
     Public KeoHangKhoPI As Boolean 
     Public KeoHangNgam As Boolean 
     Public KiemTraNutSF As Boolean 
     Public Reflow As Boolean 
     Public TachHang As Boolean 
     Public DoSongSong As Boolean 
     Public DoBr As Boolean 
     Public Other As Boolean 
     Public DoDongTam As Boolean 
     Public TearTest As Boolean 
     Public KeoCL As Boolean 
     Public MucDich As String 
     Public SoLuong As  Integer 
     Public NgayYC As DateTime 
     Public NgayRS As DateTime 
     Public Finished As Boolean 
     Public BanVe1 As String 
     Public BanVe2 As String 
     Public BanVe3 As String 
     Public BanVe4 As String 
     Public BanVeFile1 As String 
     Public BanVeFile2 As String 
     Public BanVeFile3 As String 
     Public BanVeFile4 As String 
     Public KQ1 As String 
     Public KQ2 As String 
     Public KQ3 As String 
     Public KQ4 As String 
     Public KQFile1 As String 
     Public KQFile2 As String 
     Public KQFile3 As String 
     Public KQFile4 As String 
 End  Class
