
 Public Class PD_CompleteProcess
     Public ProductCode_K As String 
     Public roisang1 As String 
     Public roisang2 As String 
     Public inmuc As String 
     Public etching1 As String 
     Public etching2 As String 
     Public plasma As String 
     Public laser As String 
     Public pth As String 
     Public dotlo As String 
     Public xulyuv As String 
     Public thumach1 As String 
     Public preset As String 
     Public say As String 
     Public entek As String 
     Public niau As String 
     Public tafue As String 
     Public cls00 As String 
     Public cls01 As String 
     Public kiem1 As String 
     Public clu00 As String 
     Public dot3 As String 
     Public giaap As String 
     Public phanloai As String 
     Public catS00 As String 
     Public catC00 As String 
     Public lami As String 
     Public developresist As String 
     Public ssexposurefirst As String 
     Public tapemask As String 
     Public softet1 As String 
     Public softet2 As String 
     Public softet3 As String 
     Public kiemdangtam As String 
     Public daptapemask As String 
     Public randomsample As String 
     Public tapemask2 As String 
     Public laserdirect As String 
 End  Class
