
 Public Class QA_ConfirmExport
     Public Ngay As DateTime 
     Public ProductCode_K As String 
     Public LotNo_K As String 
     Public Phong As String 
     Public PR3ID As String 
     Public PR3Date As DateTime 
     Public PR3Comment As String 
     Public RMID As String 
     Public RMDate As DateTime 
     Public RMComment As String 
     Public AEID As String 
     Public AEDate As DateTime 
     Public AEComment As String 
     Public DDTID As String 
     Public DDTDate As DateTime 
     Public DDTComment As String 
     Public NgayTao As DateTime 
     Public LoaiHang As String 
     Public QuaHan As Boolean 
     Public ShipTo As String 
     Public CustomerName As String 
     Public ProductName As String 
     Public NgayKiem As DateTime 
     Public IsEntek As Boolean 
     Public EntekTafueDate As DateTime 
     Public Machine As String 
     Public ChinhPham As  Integer 
     Public PhePham As  Integer 
     Public AQL As  Integer 
     Public DanhGia As String 
     Public PTHDate As DateTime 
     Public NgayKiemMau As DateTime 
     Public NhanVien As String 
     Public NiAu As String 
     Public ThietHan As String 
     Public Entek As String 
     Public TafueSU As String 
     Public MienDem As String 
     Public KeoDan As String 
     Public FPC As String 
     Public DoDayChanCam As String 
     Public ALFPC As String 
     Public SoLo As String 
     Public KyTu As String 
     Public NepGap As String 
     Public TrangThaiSuCo As String 
     Public DuongCatVPhu As String 
     Public CrossAfterPTH As String 
     Public CrossAfterOutgoing As String 
     Public Oildip As String 
     Public CrossPTHDate As DateTime 
     Public PLDate As DateTime 
     Public OildipDate As DateTime 
     Public Creeptest10gram As String 
     Public Creeptest5gram As String 
     Public UltraSonicInktest As String 
     Public TSBU As String 
     Public TSB As String 
     Public WD As String 
     Public Date10gr As DateTime 
     Public Date5gr As DateTime 
     Public DateInk As DateTime 
     Public DateTSB As DateTime 
     Public DateWD As DateTime 
     Public CrossAfterPTHA As String 
     Public CrossAfterOutgoingA As String 
     Public OildipA As String 
     Public Creeptest10gramA As String 
     Public Creeptest5gramA As String 
     Public UltraSonicInktestA As String 
     Public TSBAU As String 
     Public TSBA As String 
     Public WDA As String 
     Public CrossAfterPTHC As String 
     Public CrossAfterOutgoingC As String 
     Public OildipC As String 
     Public Creeptest10gramC As String 
     Public Creeptest5gramC As String 
     Public UltraSonicInktestC As String 
     Public TSBCU As String 
     Public TSBC As String 
     Public WDC As String 
     Public FinalEvaAE As String 
     Public AErequire As String 
     Public TestReportPath As String 
     Public TestReportPathQA As String 
     Public KetLuan As String 
     Public RMIDL As String 
     Public RMDateL As DateTime 
     Public RMCommentL As String 
     Public RMA As String 
     Public AEIDL As String 
     Public AEDateL As DateTime 
     Public AECommentL As String 
     Public AEA As String 
     Public DDTIDL As String 
     Public DDTDateL As DateTime 
     Public DDTCommentL As String 
     Public DDTA As String 
     Public Mau1 As Decimal 
     Public Mau2 As Decimal 
     Public Mau3 As Decimal 
     Public TraQT As String 
 End  Class
