
 Public Class QAE_Abnormal
    Public ID_K As String
    Public Section As String
    Public RequestDate As DateTime
    Public CurrentID As String
    Public PIC As String
    Public PICComment As String
    Public PICDate As DateTime
    Public Checked As String
    Public CheckedComment As String
    Public CheckedDate As DateTime
    Public Approved As String
    Public ApprovedComment As String
    Public ApprovedDate As DateTime
    Public QAPIC As String
    Public QAPICComment As String
    Public QAPICDate As DateTime
    Public QAChecked As String
    Public QACheckedComment As String
    Public QACheckedDate As DateTime
    Public QAApproved As String
    Public QAApprovedComment As String
    Public QAApprovedDate As DateTime
    Public PreKQ As String
    Public PreDateKQ As DateTime
    Public PreCommentKQ As String
    Public CheckedKQ As String
    Public CheckedDateKQ As DateTime
    Public CheckedCommentKQ As String
    Public ApprovedKQ As String
    Public ApprovedDateKQ As DateTime
    Public ApprovedCommentKQ As String
    Public PicQAKQ As String
    Public PicDateQAKQ As DateTime
    Public PicCommentQAKQ As String
    Public CheckedQAKQ As String
    Public CheckedDateQAKQ As DateTime
    Public CheckedCommentQAKQ As String
    Public ApprovedQAKQ As String
    Public ApprovedDateQAKQ As DateTime
    Public ApprovedCommentQAKQ As String
    Public MaThietBi As String
    Public TenThietBiDoV As String
    Public NgayPhatSinh As DateTime
    Public DealingDate As DateTime
    Public DealingDate2 As DateTime
    Public DealingDate3 As DateTime
    Public DealingDate4 As DateTime
    Public DealingDate5 As DateTime
    Public NoiDung As String
    Public SanPhamDo As String
    Public MucDichDo As String
    Public ThuocTinhDo As String
    Public ChuanSanPham As String
    Public XacNhanAnhHuong As String
    Public XacNhanKhongAnhHuong As String
    Public PhamViSanPhamKhongPhuHop As String
    Public KQXacNhanQA As String
    Public XuLySanPham As String
    Public BaoCaoKhachHang As String
    Public XuLyDungCu As String
    Public XuLyDungCuKhac As String
    Public AttachedFile As String
    Public AttachedFileServer As String
    Public DanhGiaNgoaiQuan As String
    Public DanhGiaChucNang As String
    Public DanhGiaTong As String
    Public XuLySauCung As String
    Public Remark As String
    Public AttachedFileFinish As String
    Public AttachedFileFinishServer As String
    Public CreatedDate As DateTime
    Public CreatedUser As String
End  Class
