
 Public Class pt_ASOrderTemporary
     Public PlanYear_K As  Integer 
     Public PlanWeek_K As  Integer 
     Public SalesOrderNumber_K As String 
     Public ShipType As String 
     Public ProductClass As String 
     Public MainCategoryCode As String 
     Public SubCategoryCode As String 
     Public ItemCode As String 
     Public ItemName As String 
     Public ItemNumberName As String 
     Public StandardName As String 
     Public Remarks As String 
     Public ReceivedDate As DateTime 
     Public DeliveryDate As DateTime 
     Public UnitCode As String 
     Public OrderQuantity As double
     Public OrderBalanceQuantity As double
     Public ReservedQuantity As double
     Public InstructedQuantity As double
     Public DeliveredQuantity As double
     Public ShippedQuantity As double
     Public CurrencyCode As String 
     Public UnitPrice As double
     Public SoldCode As String 
     Public SoldName As String 
     Public SoldNameAbbreviation As String 
     Public ShipCode As String 
     Public ShipName As String 
     Public ShipNameAbbreviation As String 
     Public BillCode As String 
     Public BillName As String 
     Public BillNameAbbreviation As String 
     Public CustomerOrderNumber As String 
     Public ReferenceNumber As String 
     Public PaymentCode As String 
     Public IncotermsCode As String 
     Public ShipTypeName As String 
     Public HoldFlag As String 
     Public CreatedDate As DateTime 
     Public ChangedDate As DateTime 
     Public EntryDate As DateTime 
     Public ItemType As String 
     Public FpicsCompleteQuantity As  Integer 
     Public NewFlag As String 
     Public UpdShipToFlag As String 
     Public UpdETAFlag As String 
     Public UpdQtyFlag As String 
     Public DelAllShippedFlag As String 
     Public DelCancelFlag As String 
 End  Class
