
 Public Class PLM_BOM_Stk
     Public Tuan_K As DateTime 
     Public PdCode_K As String 
     Public RC_K As String 
     Public CC_K As String 
     Public PN_K As String 
     Public ItemCode_K As String 
     Public ProcessCode As String 
     Public StdQty As Decimal 
     Public CreateDate As DateTime 
     Public CreatUser As String 
     Public DT1 As  Integer 
     Public DT2 As  Integer 
     Public DT3 As  Integer 
     Public DT4 As  Integer 
     Public DT5 As  Integer 
     Public DT6 As  Integer 
     Public DT7 As  Integer 
     Public DT8 As  Integer 
     Public DT9 As  Integer 
     Public DT10 As  Integer 
     Public DT11 As  Integer 
     Public DT12 As  Integer 
     Public DT13 As  Integer 
     Public DT14 As  Integer 
     Public DT15 As  Integer 
     Public DT16 As  Integer 
     Public DT17 As  Integer 
     Public DT18 As  Integer 
     Public DT19 As  Integer 
     Public DT20 As  Integer 
     Public DT21 As  Integer 
     Public DT22 As  Integer 
     Public DT23 As  Integer 
     Public DT24 As  Integer 
     Public FG As  Integer 
     Public WIP As  Integer 
     Public XH1 As  Integer 
     Public XH2 As  Integer 
     Public XH3 As  Integer 
     Public XH4 As  Integer 
     Public XH5 As  Integer 
     Public XH6 As  Integer 
     Public XH7 As  Integer 
     Public XH8 As  Integer 
     Public XH9 As  Integer 
     Public XH10 As  Integer 
     Public XH11 As  Integer 
     Public XH12 As  Integer 
     Public XH13 As  Integer 
     Public XH14 As  Integer 
     Public XH15 As  Integer 
     Public XH16 As  Integer 
     Public XH17 As  Integer 
     Public XH18 As  Integer 
     Public XH19 As  Integer 
     Public XH20 As  Integer 
     Public XH21 As  Integer 
     Public XH22 As  Integer 
     Public XH23 As  Integer 
     Public XH24 As  Integer 
 End  Class
