
 Public Class CP_ImportPO
     Public ProcessCode_K As String 
     Public Ngay As DateTime 
     Public Customer As String 
     Public ProductCode_K As String 
     Public StartLot As  Integer 
     Public T1 As  Integer 
     Public T2 As  Integer 
     Public T3 As  Integer 
     Public T4 As  Integer 
     Public T5 As  Integer 
     Public T6 As  Integer 
     Public T7 As  Integer 
     Public T8 As  Integer 
     Public T9 As  Integer 
     Public T10 As  Integer 
     Public T11 As  Integer 
     Public T12 As  Integer 
     Public T13 As  Integer 
     Public T14 As  Integer 
     Public T15 As  Integer 
     Public T16 As  Integer 
     Public T17 As  Integer 
     Public T18 As  Integer 
     Public T19 As  Integer 
     Public T20 As  Integer 
     Public T21 As  Integer 
     Public T22 As  Integer 
     Public T23 As  Integer 
     Public T24 As  Integer 
     Public T25 As  Integer 
     Public T26 As  Integer 
     Public T27 As  Integer 
     Public T28 As  Integer 
     Public T29 As  Integer 
     Public T30 As  Integer 
     Public L1 As  Integer 
     Public L2 As  Integer 
     Public L3 As  Integer 
     Public L4 As  Integer 
     Public L5 As  Integer 
     Public L6 As  Integer 
     Public L7 As  Integer 
     Public L8 As  Integer 
     Public L9 As  Integer 
     Public L10 As  Integer 
     Public L11 As  Integer 
     Public L12 As  Integer 
     Public L13 As  Integer 
     Public L14 As  Integer 
     Public L15 As  Integer 
     Public L16 As  Integer 
     Public L17 As  Integer 
     Public L18 As  Integer 
     Public L19 As  Integer 
     Public L20 As  Integer 
     Public L21 As  Integer 
     Public L22 As  Integer 
     Public L23 As  Integer 
     Public L24 As  Integer 
     Public L25 As  Integer 
     Public L26 As  Integer 
     Public L27 As  Integer 
     Public L28 As  Integer 
     Public L29 As  Integer 
     Public L30 As  Integer 
     Public EndLot As  Integer 
     Public K1 As  Integer 
     Public K2 As  Integer 
     Public K3 As  Integer 
     Public K4 As  Integer 
     Public K5 As  Integer 
     Public K6 As  Integer 
     Public K7 As  Integer 
     Public K8 As  Integer 
     Public K9 As  Integer 
     Public K10 As  Integer 
     Public K11 As  Integer 
     Public K12 As  Integer 
     Public K13 As  Integer 
     Public K14 As  Integer 
     Public K15 As  Integer 
     Public K16 As  Integer 
     Public K17 As  Integer 
     Public K18 As  Integer 
     Public K19 As  Integer 
     Public K20 As  Integer 
     Public K21 As  Integer 
     Public K22 As  Integer 
     Public K23 As  Integer 
     Public K24 As  Integer 
     Public K25 As  Integer 
     Public K26 As  Integer 
     Public K27 As  Integer 
     Public K28 As  Integer 
     Public K29 As  Integer 
     Public K30 As  Integer 
     Public StartLot2 As  Integer 
     Public F1 As  Integer 
     Public F2 As  Integer 
     Public F3 As  Integer 
     Public F4 As  Integer 
     Public F5 As  Integer 
     Public F6 As  Integer 
     Public F7 As  Integer 
     Public F8 As  Integer 
     Public F9 As  Integer 
     Public F10 As  Integer 
     Public F11 As  Integer 
     Public F12 As  Integer 
     Public F13 As  Integer 
     Public F14 As  Integer 
     Public F15 As  Integer 
     Public F16 As  Integer 
     Public F17 As  Integer 
     Public F18 As  Integer 
     Public F19 As  Integer 
     Public F20 As  Integer 
     Public F21 As  Integer 
     Public F22 As  Integer 
     Public F23 As  Integer 
     Public F24 As  Integer 
     Public F25 As  Integer 
     Public F26 As  Integer 
     Public F27 As  Integer 
     Public F28 As  Integer 
     Public F29 As  Integer 
     Public F30 As  Integer 
 End  Class
