
 Public Class AD_QA_HDCV
     Public ID_K As String 
     Public Section As String 
     Public NgayTao As DateTime 
     Public DocNo As String 
     Public DocRev As String 
     Public DocName As String 
     Public PathFile As String 
     Public CreateID As String 
     Public CreateEmail As String 
     Public CreateComment As String 
     Public CreateDate As DateTime 
     Public GLID As String 
     Public GLEmail As String 
     Public GLComment As String 
     Public GLDate As DateTime 
     Public MGCID As String 
     Public MGCEmail As String 
     Public MGCComment As String 
     Public MGCDate As DateTime 
     Public MCCID As String 
     Public MCCEmail As String 
     Public MCCComment As String 
     Public MCCDate As DateTime 
     Public TKID1 As String 
     Public TKEmail1 As String 
     Public TKComment1 As String 
     Public TKDate1 As DateTime 
     Public TKID2 As String 
     Public TKEmail2 As String 
     Public TKComment2 As String 
     Public TKDate2 As DateTime 
     Public TKID3 As String 
     Public TKEmail3 As String 
     Public TKComment3 As String 
     Public TKDate3 As DateTime 
     Public TKID4 As String 
     Public TKEmail4 As String 
     Public TKComment4 As String 
     Public TKDate4 As DateTime 
     Public TKID5 As String 
     Public TKEmail5 As String 
     Public TKComment5 As String 
     Public TKDate5 As DateTime 
     Public TKID6 As String 
     Public TKEmail6 As String 
     Public TKComment6 As String 
     Public TKDate6 As DateTime 
     Public TKID7 As String 
     Public TKEmail7 As String 
     Public TKComment7 As String 
     Public TKDate7 As DateTime 
     Public TKID8 As String 
     Public TKEmail8 As String 
     Public TKComment8 As String 
     Public TKDate8 As DateTime 
     Public MGAID As String 
     Public MGAEmail As String 
     Public MGAComment As String 
     Public MGADate As DateTime 
     Public MCAID As String 
     Public MCAEmail As String 
     Public MCAComment As String 
     Public MCADate As DateTime 
     Public CurrentID As String 
 End  Class
