
 Public Class t_ASPurchaseOrderHeadHistory
     Public PurchaseOrderNumber_K As String 
     Public ReviseCount As  Integer 
     Public ShipType As String 
     Public VendorCode As String 
     Public PayCode As String 
     Public WarehouseCode As String 
     Public WarehouseType As String 
     Public PrintedPurchaseOrderNumber As String 
     Public CustomerOrderNumber As String 
     Public SoldCode As String 
     Public ShipCode As String 
     Public IssuedDate As DateTime 
     Public ReviseIssuedDate As DateTime 
     Public ExchangeRate As double
     Public ReplacePurchaseOrderNumber As String 
     Public MainCategoryCode As String 
     Public BrandName As String 
     Public CurrencyCode As String 
     Public PaymentCode As String 
     Public IncotermsCode As String 
     Public SalesPoint As String 
     Public SellingCurrencyCode As String 
     Public SellingPaymentCode As String 
     Public SellingIncotermsCode As String 
     Public SellingSalesPoint As String 
     Public ShipmentBy As String 
     Public InsuranceRate As  Integer 
     Public Destination As String 
     Public ConsigneeCode As String 
     Public NotifyCode As String 
     Public DocumentSendCode As String 
     Public CarrierCode As String 
     Public CarrierAccountNumber As String 
     Public PartialShipFlag As String 
     Public DeliveryScheduleFlag As String 
     Public SampleFlag As String 
     Public HoldFlag As String 
     Public EDIVendorFlag As String 
     Public DataSentFlag As String 
     Public CompletedDate As DateTime 
     Public PrintStatus As String 
     Public ChangeStatus As String 
     Public PrintStatus2 As String 
     Public CancelReasonCode As String 
     Public CanceledUserCode As String 
     Public CanceledTransactionNumber As String 
     Public CanceledDate As DateTime 
     Public AnswerDate As DateTime 
     Public BuyerCode As String 
     Public TaxFlag As String 
     Public TaxType As String 
     Public CreatedUserCode As String 
     Public CreatedTransactionNumber As String 
     Public CreatedDate As DateTime 
     Public ChangedUserCode As String 
     Public ChangedTransactionNumber As String 
     Public ChangedDate As DateTime 
     Public DeletedUserCode As String 
     Public DeletedTransactionNumber As String 
     Public DeletedDate As DateTime 
 End  Class
