
 Public Class t_ASProductItem
     Public ItemCode_K As String 
     Public ItemName As String 
     Public ProductClass As String 
     Public MainCategoryCode As String 
     Public SubCategoryCode As String 
     Public ItemGroupCode As String 
     Public ItemGroupCode2 As String 
     Public ItemNumberName As String 
     Public StandardName As String 
     Public ColorName As String 
     Public CustomerPartNumber As String 
     Public Remarks As String 
     Public SoldCode As String 
     Public VendorCode As String 
     Public UnitCode As String 
     Public PackageUnitCode As String 
     Public QuantityParCarton As double
     Public QuantityParPallet As double
     Public SellingMinimumQuantity As double
     Public BuyingMinimumQuantity As double
     Public OrderPointQuantity As double
     Public OriginCountryName As String 
     Public LeadTime As  Integer 
     Public RefrigerationFlag As String 
     Public ItemSignFlag As String 
     Public SalesFlag As String 
     Public StockControlFlag As String 
     Public TaxFlag As String 
     Public MainAccountCode As String 
     Public SubAccountCode As String 
     Public NetWeight As double
     Public GUCItemNumberCode As String 
     Public GUCStandardCode As String 
     Public GUCSalesUnitCode As String 
     Public GUCCategoryCode As String 
     Public SAPItemCode As String 
     Public CreatedUserCode As String 
     Public CreatedTransactionNumber As String 
     Public CreatedDate As DateTime 
     Public ChangedUserCode As String 
     Public ChangedTransactionNumber As String 
     Public ChangedDate As DateTime 
     Public DeletedUserCode As String 
     Public DeletedTransactionNumber As String 
     Public DeletedDate As DateTime 
     Public ItemType As String 
 End  Class
