
 Public Class BS_NhanVienDi
     Public ID_K As String 
     Public MaNV As String 
     Public TenNV As String 
     Public ChucVu As String 
     Public PhongBan As String 
     Public RingNo As String 
     Public NoiDiCongTac As String 
     Public DiaChiEmail As String 
     Public HangHangKhongDi As String 
     Public HangHangKhongVe As String 
     Public DaiLyVe As String 
     Public NgayPhatHanhVe As DateTime 
     Public GiaVe As Decimal 
     Public DaThanhToanVe As Boolean 
     Public NgayDi As DateTime 
     Public ChuyenBayDi As String 
     Public GioDi As DateTime 
     Public GaDi As String 
     Public NoiXuatPhat As String 
     Public NgayVe As DateTime 
     Public ChuyenBayVe As String 
     Public GioVe As DateTime 
     Public GaVe As String 
     Public NoiDuaVe As String 
     Public CanXeDuaDonSanBay As Boolean 
     Public XeDon As String 
     Public TaiXeDon As String 
     Public SDTDon As String 
     Public LoaiXeDon As String 
     Public BienSoXeDon As String 
     Public KhachDiChungXeDon As String 
     Public XeTien As String 
     Public TaiXeTien As String 
     Public SDTTien As String 
     Public LoaiXeTien As String 
     Public BienSoXeTien As String 
     Public KhachDiChungXeTien As String 
     Public CanKhachSan As Boolean 
     Public SoNgayLuuTru As  Integer 
     Public TenKhachSan As String 
     Public LoaiPhong As String 
     Public GiaPhong1Dem As Decimal 
     Public GiaXeDonSanBay As Decimal 
     Public GiatUi As  Integer 
     Public TraPhongTre As String 
     Public GioTraPhongTre As DateTime 
     Public PhongHutThuoc As String 
     Public NguoiThanhToan As String 
     Public GiaXeTienSanBay As Decimal 
     Public UuDaiKhac As String 
     Public CanAoKhoac As Boolean 
     Public SizeAo As String 
     Public YeuCauKhac As String 
     Public CanDienThoai As Boolean 
     Public HangSanXuat As String 
     Public NgayMuonDT As DateTime 
     Public NgayTraDT As DateTime 
     Public SoIMEI As String 
     Public CanSim As Boolean 
     Public NhaMang As String 
     Public SimSo As String 
     Public NgayMuonSim As DateTime 
     Public NgayTraSim As DateTime 
     Public CanQuaTangKhach As Boolean 
     Public SoPhanQua As String 
     Public TongChiPhi As Decimal 
     Public CanHoChieu As Boolean 
     Public NHSPassport As Boolean 
     Public NKQPassport As Boolean 
     Public NgayTraKQPassport As DateTime 
     Public HinhPassport As String 
     Public CanVisa As Boolean 
     Public NHSVisa As Boolean 
     Public NKQVisa As Boolean 
     Public NgayTraKQVisa As DateTime 
     Public HinhVisa As String 
     Public GhiChu As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public CurrentID As String 
     Public MailRQ As String 
     Public MailAP As String 
     Public DateRQ As DateTime 
     Public DateAP As DateTime 
 End  Class
