
 Public Class ASP_QuotationRequestHead
     Public QRNo_K As String 
     Public RequestSection As String 
     Public RequestDate As DateTime 
     Public Prepared As String 
     Public PreparedComment As String 
     Public PreparedStatus As Boolean 
     Public PreparedDate As DateTime 
     Public Approved As String 
     Public ApprovedComment As String 
     Public ApprovedStatus As Boolean 
     Public ApprovedDate As DateTime 
     Public PUChecked As String 
     Public PUCheckedComment As String 
     Public PUCheckedStatus As Boolean 
     Public PUCheckedDate As DateTime 
     Public PUSearched As String 
     Public PUSearchedComment As String 
     Public PUSearchedStatus As Boolean 
     Public PUSearchedDate As DateTime 
     Public PULeaderChecked As String 
     Public PULeaderCheckedComment As String 
     Public PULeaderCheckedStatus As Boolean 
     Public PULeaderCheckedDate As DateTime 
     Public PUApproved As String 
     Public PUApprovedComment As String 
     Public PUApprovedStatus As Boolean 
     Public PUApprovedDate As DateTime 
     Public PUQRNo As String 
     Public Note As String 
     Public Cancel As Boolean 
     Public CancelUser As String 
     Public Deleted As Boolean 
     Public DeletedUser As String 
     Public CreateUser As String 
     Public CreateDate As DateTime 
     Public NewQDate As DateTime 
     Public Evidence As String 
     Public EvidenceServer As String 
     Public LoaiYeuCau As String 
 End  Class
