
 Public Class QAE_Register
     Public ID_K As String 
     Public Section As String 
     Public RequestDate As DateTime 
     Public CurrentID As String 
     Public PIC As String 
     Public PICComment As String 
     Public PICDate As DateTime 
     Public Checked As String 
     Public CheckedComment As String 
     Public CheckedDate As DateTime 
     Public Approved As String 
     Public ApprovedComment As String 
     Public ApprovedDate As DateTime 
     Public QAPIC As String 
     Public QAPICComment As String 
     Public QAPICDate As DateTime 
     Public QAChecked As String 
     Public QACheckedComment As String 
     Public QACheckedDate As DateTime 
     Public QAApproved As String 
     Public QAApprovedComment As String 
     Public QAApprovedDate As DateTime 
     Public NoiDatThietBi As String 
     Public MaThietBiDo As String 
     Public TenThietBiDoV As String 
     Public TenThietBiDoE As String 
     Public Model As String 
     Public SerialNo As String 
     Public NhaSanXuat As String 
     Public DoPhanGiai As String 
     Public PhamViDo As String 
     Public HangMucDo As String 
     Public SanPhamDo As String 
     Public NgayNhanThietBi As DateTime 
     Public ChungNhanChatLuong As String 
     Public LoaiHinhDangLuc As String 
     Public Khac As String 
     Public AttachedFile As String 
     Public AttachedFileServer As String 
     Public GioiHanHieuChuan As String 
     Public ThongTinThietBiChuan As String 
     Public QuyCachHieuChuan As String 
     Public SaiSoDo As String 
     Public DanhGia As String 
     Public ChuKyHieuChuan As String 
     Public LoaHieuChuan As String 
     Public NoiHieuChuan As String 
     Public Accessories As String 
     Public CurrentCalibDate As DateTime 
     Public NextCalibDate As DateTime 
     Public GhiChu As String 
     Public AttachedFileQA As String 
     Public AttachedFileServerQA As String 
     Public CreatedDate As DateTime 
     Public CreatedUser As String 
 End  Class
