
 Public Class t_ASSalesOrderHead
     Public SalesOrderNumber_K As String 
     Public ReviseCount As  Integer 
     Public ShipType As String 
     Public DeliveryScheduleFlag As String 
     Public PurchaseOrderNumber As String 
     Public ReferenceNumber As String 
     Public ReceivedDate As DateTime 
     Public CompletedDate As DateTime 
     Public SoldCode As String 
     Public SoldName As String 
     Public ShipCode As String 
     Public ShipName As String 
     Public BillCode As String 
     Public BillName As String 
     Public CustomerOrderNumber As String 
     Public MainCategoryCode As String 
     Public BuyerName As String 
     Public PartialShipFlag As String 
     Public OrderConfirmationFlag As String 
     Public CurrencyCode As String 
     Public PaymentCode As String 
     Public IncotermsCode As String 
     Public SalesPoint As String 
     Public ShipTypeName As String 
     Public SalesCode As String 
     Public TaxFlag As String 
     Public WarehouseCode As String 
     Public WarehouseType As String 
     Public ConsigneeCode As String 
     Public NotifyCode As String 
     Public DocumentSendCode As String 
     Public CarrierCode As String 
     Public CarrierAccountNumber As String 
     Public HoldFlag As String 
     Public HoldReleasedDate As DateTime 
     Public HoldReleasedUserName As String 
     Public BillHoldFlag As String 
     Public PrintStatus As String 
     Public ChangeStatus As String 
     Public CancelReasonCode As String 
     Public CanceledUserCode As String 
     Public CanceledTransactionNumber As String 
     Public CanceledDate As DateTime 
     Public CreatedUserCode As String 
     Public CreatedTransactionNumber As String 
     Public CreatedDate As DateTime 
     Public ChangedUserCode As String 
     Public ChangedTransactionNumber As String 
     Public ChangedDate As DateTime 
     Public DeletedUserCode As String 
     Public DeletedTransactionNumber As String 
     Public DeletedDate As DateTime 
 End  Class
