
 Public Class t_ASMaterialInOutHistory
     Public TransactionNumber_K As String 
     Public TransactionSequenceNumber_K As  Integer 
     Public TransactionType As String 
     Public TransactionDate As DateTime 
     Public PurchaseNumber As String 
     Public PurchaseDate As DateTime 
     Public ReferenceNumber As String 
     Public ReferenceSequenceNumber As  Integer 
     Public ReferenceNumber2 As String 
     Public SalesOrderNumber As String 
     Public PurchaseOrderNumber As String 
     Public PurchaseOrderLineNumber As  Integer 
     Public SoldCode As String 
     Public WarehouseCode As String 
     Public WarehouseType As String 
     Public TargetCode As String 
     Public TargetType As String 
     Public MainCategoryCode As String 
     Public SubCategoryCode As String 
     Public ItemCode As String 
     Public Remarks As String 
     Public StoreNumber As String 
     Public LotNumber As String 
     Public Quantity As double
     Public UnitCode As String 
     Public CartonQuantity As double
     Public VendorCode As String 
     Public UnitPrice As double
     Public TotalAmount As double
     Public ProcessMonth As String 
     Public PrintStatus As String 
     Public CreatedUserCode As String 
     Public CreatedTransactionNumber As String 
     Public CreatedDate As DateTime 
     Public ChangedUserCode As String 
     Public ChangedTransactionNumber As String 
     Public ChangedDate As DateTime 
     Public DeletedUserCode As String 
     Public DeletedTransactionNumber As String 
     Public DeletedDate As DateTime 
 End  Class
