
 Public Class PD_LeadtimeLot
     Public ProductCode_K As String 
     Public roisang1 As Decimal 
     Public roisang2 As Decimal 
     Public inmuc As Decimal 
     Public etching1 As Decimal 
     Public etching2 As Decimal 
     Public plasma As Decimal 
     Public laser As Decimal 
     Public pth As Decimal 
     Public dotlo As Decimal 
     Public xulyuv As Decimal 
     Public thumach1 As Decimal 
     Public preset As Decimal 
     Public say As Decimal 
     Public entek As Decimal 
     Public niau As Decimal 
     Public tafue As Decimal 
     Public cls00 As Decimal 
     Public cls01 As Decimal 
     Public kiem1 As Decimal 
     Public clu00 As Decimal 
     Public dot3 As Decimal 
     Public giaap As Decimal 
     Public phanloai As Decimal 
     Public catS00 As Decimal 
     Public catC00 As Decimal 
     Public lami As Decimal 
     Public developresist As Decimal 
     Public ssexposurefirst As Decimal 
     Public tapemask As Decimal 
     Public softet1 As Decimal 
     Public softet2 As Decimal 
     Public softet3 As Decimal 
     Public kiemdangtam As Decimal 
     Public daptapemask As Decimal 
     Public randomsample As Decimal 
     Public tapemask2 As Decimal 
     Public laserdirect As Decimal 
 End  Class
