
 Public Class QAE_Verify
     Public ID_K As String 
     Public Section As String 
     Public RequestDate As DateTime 
     Public CurrentID As String 
     Public PIC As String 
     Public PICComment As String 
     Public PICDate As DateTime 
     Public Checked As String 
     Public CheckedComment As String 
     Public CheckedDate As DateTime 
     Public Approved As String 
     Public ApprovedComment As String 
     Public ApprovedDate As DateTime 
     Public QAPIC As String 
     Public QAPICComment As String 
     Public QAPICDate As DateTime 
     Public QAChecked As String 
     Public QACheckedComment As String 
     Public QACheckedDate As DateTime 
     Public QAApproved As String 
     Public QAApprovedComment As String 
     Public QAApprovedDate As DateTime 
     Public NoiDeNghi As String 
     Public TenThietBi As String 
     Public MucDichSuDung As String 
     Public PhamViSuDung As String 
     Public GiaTriSuDungNhoNhat As String 
     Public DoPhanGiaiChoThietBi As String 
     Public ThietBiDoLuongCoKiemSoat As Boolean 
     Public ThietBiDoLuongKhongKiemSoat As Boolean 
     Public PhieuXacNhanChatLuong As Boolean 
     Public KetQuaKiemTraThietBiDo As Boolean 
     Public GiayToKhac As String 
     Public KhongCan As Boolean 
     Public GhiChu As String 
     Public AttachedFile As String 
     Public AttachedFileServer As String 
     Public CreatedDate As DateTime 
     Public CreatedUser As String 
 End  Class
