
 Public Class UDM_LogisticsPaymentDocs
     Public CDNo_K As String 
     Public RegDate_K As DateTime 
     Public Mode_K As  Integer 
     Public CDType_K As String 
     Public Domestics As Decimal 
     Public Trucking As Decimal 
     Public CSFormality As Decimal 
     Public CFS As Decimal 
     Public SpecialHandlingCharge As Decimal 
     Public StorageCharge As Decimal 
     Public SpecialStorageCharge As Decimal 
     Public THC As Decimal 
     Public PortCharge As Decimal 
     Public Detention As Decimal 
     Public Demurrage As Decimal 
     Public OceanFee As Decimal 
     Public AirFee As Decimal 
     Public LocalCharge As Decimal 
     Public DestinationCharge As Decimal 
     Public FOBCharge As Decimal 
     Public AMSVND As Decimal 
     Public CustomsClearanceVND As Decimal 
     Public InspectionVND As Decimal 
     Public TruckingVND As Decimal 
     Public XRayVND As Decimal 
     Public DOFee As Decimal 
     Public BLOrAWB As Decimal 
     Public Serrender As Decimal 
     Public TelexRelease As Decimal 
     Public LiftOnOrLiftOff As Decimal 
     Public TerminalFee As Decimal 
     Public Fuel As Decimal 
     Public Security As Decimal 
     Public CIC As Decimal 
     Public PortChargeVND As Decimal 
     Public InlandCharge As Decimal 
     Public CustomsClearance As Decimal 
     Public AirFeeVND As Decimal 
     Public DutyAndTax As Decimal 
     Public Packing As Decimal 
     Public Fumigation As Decimal 
     Public Seal As Decimal 
     Public ExpressHandlingCharge As Decimal 
     Public OvertimeCharge As Decimal 
     Public OvertimeSunday As Decimal 
     Public OvertimeInspection As Decimal 
     Public XRay As Decimal 
     Public QualityInspection As Decimal 
     Public UnloadingCharge As Decimal 
     Public EnvironmentalTax As Decimal 
     Public AFR As Decimal 
     Public Handling As Decimal 
     Public VacummPacking As Decimal 
     Public ExtraHAWB As Decimal 
     Public TerminalStorageChargeVAT As String 
     Public TerminalChargeVAT As String 
     Public AirImportFreightVAT As String 
     Public DocumentFeeVAT As String 
     Public VATFreight As String 
     Public VATTax As String 
     Public VATDO As String 
     Public BLNo As String 
     Public BLDate As DateTime 
     Public Note As String 
     Public PaymentPeriod As String 
     Public IsLock As Boolean 
     Public LockUser As String 
     Public LockDate As DateTime 
     Public UnlockUser As String 
     Public UnlockDate As DateTime 
     Public Remark As String 
     Public Rate As Decimal 
     Public Idx As  Integer 
     Public LogisticsType As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public UpdateDate As DateTime 
     Public UpdateUser As String 
 End  Class
