
 Public Class DOC_Document
     Public DocNo_K As String 
     Public DocRev_K As String 
     Public DocType As String 
     Public DocName As String 
     Public Section As String 
     Public Customer As String 
     Public Author As String 
     Public Path As String 
     Public Note As String 
     Public Check5Y As Boolean 
     Public FinishedDate As DateTime 
     Public Valid As DateTime 
     Public Invalid As DateTime 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public Total As  Integer 
     Public TotalFile As  Integer 
     Public QA As  Integer 
     Public QC As  Integer 
     Public QC_GATE As  Integer 
     Public IQC As  Integer 
     Public CS As  Integer 
     Public MT As  Integer 
     Public AE As  Integer 
     Public OQC As  Integer 
     Public OQA As  Integer 
     Public PC As  Integer 
     Public PR As  Integer 
     Public PR1 As  Integer 
     Public EDU1 As  Integer 
     Public CHK As  Integer 
     Public ENT As  Integer 
     Public NC1 As  Integer 
     Public NC2 As  Integer 
     Public LAM As  Integer 
     Public CLP As  Integer 
     Public PLT As  Integer 
     Public PTH As  Integer 
     Public ETC As  Integer 
     Public ANA1 As  Integer 
     Public ANA2 As  Integer 
     Public LASER As  Integer 
     Public PHOTO1 As  Integer 
     Public AOI As  Integer 
     Public PR2 As  Integer 
     Public EDU2 As  Integer 
     Public PUN As  Integer 
     Public CELL As  Integer 
     Public MP As  Integer 
     Public CL1 As  Integer 
     Public CL3 As  Integer 
     Public PR3 As  Integer 
     Public EDU3 As  Integer 
     Public INS1 As  Integer 
     Public INS2 As  Integer 
     Public PK As  Integer 
     Public PHOTO2 As  Integer 
     Public TE As  Integer 
     Public PP As  Integer 
     Public PE As  Integer 
     Public LO As  Integer 
     Public PU As  Integer 
     Public GA As  Integer 
     Public IT As  Integer 
     Public AC As  Integer 
     Public MC As  Integer 
     Public DE As  Integer 
     Public SE As  Integer 
     Public PS As  Integer 
     Public CIS_QA As  Integer 
     Public C_OQA As  Integer 
     Public IQA As  Integer 
     Public CIS_PR As  Integer 
     Public PLL As  Integer 
     Public RS As  Integer 
     Public HA As  Integer 
     Public PLM As  Integer 
     Public AMN As  Integer 
     Public MA As  Integer 
     Public AMS As  Integer 
     Public RHT As  Integer 
 End  Class
