
 Public Class DCS_Data_CIS
     Public Lock As Boolean 
     Public Type_K As String 
     Public ProductCode_K As String 
     Public ItemNo_K As String 
     Public LotNo_K As String 
     Public EntryDate As DateTime 
     Public D1 As Decimal 
     Public D2 As Decimal 
     Public D3 As Decimal 
     Public D4 As Decimal 
     Public D5 As Decimal 
     Public D6 As Decimal 
     Public D7 As Decimal 
     Public D8 As Decimal 
     Public D9 As Decimal 
     Public D10 As Decimal 
     Public D11 As Decimal 
     Public D12 As Decimal 
     Public D13 As Decimal 
     Public D14 As Decimal 
     Public D15 As Decimal 
     Public D16 As Decimal 
     Public D17 As Decimal 
     Public D18 As Decimal 
     Public D19 As Decimal 
     Public D20 As Decimal 
     Public D21 As Decimal 
     Public D22 As Decimal 
     Public D23 As Decimal 
     Public D24 As Decimal 
     Public D25 As Decimal 
     Public D26 As Decimal 
     Public D27 As Decimal 
     Public D28 As Decimal 
     Public D29 As Decimal 
     Public D30 As Decimal 
     Public D31 As Decimal 
     Public D32 As Decimal 
     Public D33 As Decimal 
     Public D34 As Decimal 
     Public D35 As Decimal 
     Public LotNumber As  Integer 
     Public OutOfControl As Boolean 
     Public Comment1 As String 
     Public Comment2 As String 
     Public StartDate As DateTime 
     Public EndDate As DateTime 
     Public TotalTime As  Integer 
     Public OperatorCode As String 
     Public CreateDate As DateTime 
     Public CreateUser As String 
     Public StartDateT As String 
     Public EndDateT As String 
 End  Class
